### ISSUE TITLE
Windows Drive Path Casing Issue

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/cli#108]
Hello,

I have a scratch org create script that does a few things including data import.

What I have noticed: The first time I push changes from VS Code to the newly created scratch org, VS Code does a full push.  Even if I changed only one file, I get the whole source push which takes quite some time. 

In summary, I wait once for a complete push in my script and then have to wait for another full push in VS Code. 

Is this behaviour to be expected?

**Comment by Szandor72** [comment]
Aha! This is were my issue ended up. :) I am still hoping to get this sorted out.

**Comment by Szandor72** [comment]
It seems `SFDX: View Local Changes` disappeared from the command palette, so this issue has no workaround any more. 

![image](https://user-images.githubusercontent.com/16804218/62774618-972a1b00-baa5-11e9-98bd-4d1f9251c451.png)

**Comment by nbendjamaa** [comment]
Hi, do you know when this issue will be fixed?

**Comment by Szandor72** [comment]
Since api v49 the situation got worse for me. 

The mentioned workaround (view local changes) stopped working for me altogether.

It seems, I am forced to do two full pushes since I am running my setup from a powershell script, that means pushing 2000 components twice - once from my command line, once in VS Code if I want to use it. I am not happy.

**Comment by aheber** [comment]
It would seem that a way forward here would be for the DX plugin to store relative paths instead of full directory paths. That would drop the drive letter entirely.

This could also have a better workaround if it the VS Code plugins exposed the the new `source:tracking:reset` command. Running that after the build script from within VS Code could take care of the miss-match.

(There are ways to get your CLI path onto `c` instead of `C` but it takes switching drive directories and some other stuff that isn't fun or consistent)

**Comment by Szandor72** [comment]
Is this issue being actively investigated? It's been two years and I still have to push 2000 Metadata Components twice into scratch orgs.

**Comment by lnoellemorgan-zz** [comment]
This bug is being tracked by work item: W-6208564

**Comment by mdonnalley** [comment]
In order to properly fix this, we'd have to normalize file paths across multiple packages and plugins. There are simply too many places that we inspect and compare file paths to implement this safely. Because of that, we're not going to fix this now. However, we may revisit this issue when we migrate the source commands to their own plugin
