### ISSUE TITLE
Scratch org login requires MFA when running OAuth automation locally

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#1236]
### Summary

It's possibly not the best place to ask, but oh well.
I'm testing OAuth flow (log into my portal, initiate OAuth from there, log into Salesforce, approve connected app) via Playwright.
Works ok in CI, but when running locally it asks for 2FA code from email, which would be horror to automate...
Wonder why this could be happening and how to avoid? Is there a quicker way to connect my app to Salesforce. I can still test the flow in CI, but I want to quickly exchange tokens between new environments.

Perhaps there's a way to use login url from `sfdx force:org:open` and forgo username/password authentication?

### Steps To Reproduce:

I'm running [this script](https://gist.github.com/sjurgis/287d3ede6aeb0ec9f8123cb7f5adf84b) to:
* generate new password for my test user
* click a button on my portal
* this redirects to test.salesforce.com/...
* login 
* (sometimes dismiss "change your password" screen)
* click "Allow"

### Expected result

No MFA is triggered. Scratch orgs should be exempt.

### Actual result

Sends a code to my email

### Additional information

New password doesn't work immediately. I have to retry logging in, sometimes 10s of times to succeed. This is why Salesforce is fun.

**Comment by mshanemc** [comment]
login servers (login. and test.) have a replication delay from when some instance creates a username/password to when they're replicated to the login server.

if you have a way to pass the scratch org's instanceUrl to your oauth flow it may be able to login immediately, if I remember correctly (you're going directly to your instance instead of from the 'generic' login which needs to know which instance.

Closing because it's not really CLI related, but I hope it works.
