### ISSUE TITLE
Push fails with "Expected file at path: force-app\main\core\ReadMe.md-meta.xml" 

### ISSUE THREAD

**Issue by reddykrupananda** [forcedotcom/cli#1277]
Summary
After updating cli version to sfdx-cli/7.125.0 win32-x64 node-v16.13.0 running force:source:push fails with the following error -
ERROR running force:source:push:
Expected file at path: C:\sfdx-demos\changes\sfdx-source\dx\main\domain\classes\README.md-meta.xml

Steps To Reproduce:
Add "**/ReadMe.*" to .forceignore file.
Add a ReadMe.md file in the under force-app\ directory
Run sfdx force:source:push to push the changes

Expected result:
It should not treat ReadMe.md file as custom metadata and it should be ignored as defined in .forceignore

Actual result
sfdx force:source:push fails with:

ERROR running force:source:push: Expected file at path: Expected file at path: C:\sfdx-demos\change\sfdx-source\dx\main\domain\classes\README.md-meta.xml

Additional Information: 
sfdx-cli/7.125.0 win32-x64 node-v16.13.0
@salesforce/analytics 1.0.1
@salesforce/sfdx-scanner 2.12.0
isvte-sfdx-plugin 1.1.12

This is already reported ([691](https://github.com/forcedotcom/cli/issues/691)) and closed without providing any resolution or workaround.

**Comment by shetzel** [comment]
I would use the `force:source:ignored:list` command with the `.forceignore` file to ensure it's ignored as expected.  The library used for ignoring files is https://www.npmjs.com/package/ignore so check with their docs on the syntax.

**Comment by mshanemc** [comment]
on windows, should that be `Add "**\ReadMe.*" to .forceignore file` ?

**Comment by reddykrupananda** [comment]
@shetzel and @mshanemc  Thanks for your responses. I did add README.Md to force.ignore for all the package directories and it solved the issue. However, expectinge md-meta.xml for a Readme file is weird. Isn't this supposed to be a bug ?

**Comment by shetzel** [comment]
@reddykrupananda - any file with a suffix of `.md` within your SFDX project's package directories will be treated as a `CustomMetadata` type because that's how the type is defined.  See https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json#L949
It's an unfortunate metadata file suffix because it's not unique outside of the world of Salesforce metadata.  However, if you don't forceignore that file it will cause other problems even if the SDR library doesn't assume it's CustomMetadata.  If you want that file to be in a package directory you *must* forceignore it.
