### ISSUE TITLE
delete and deploy the same object

### ISSUE THREAD

**Issue by kamilacc97** [forcedotcom/cli#1303]
### Summary

Problem with destructiveChangesPre and deploy. I want to delete object, for instance xyz, in destructiveChangesPre.xml and in package.xml deploy it again and it's doesn't work.

### Steps To Reproduce:

**Repository to reproduce:** https://github.com/kamilacc97/sfdxrepo

1.  pull project from link
2.  Creating object, for instance lets call it TestDeleteAndDeploy__c  (it is exist in repo)
3.  download object by visualforce on your local machine
4.  create destructiveChangesPre.xml (pathRepo: temp/destructiveChangesPre/destructiveChangesPre.xml)
5.  add TestDeleteAndDeploy__c object to destructiveChangesPre.xml 
6.  create manifest where we want deploy TestDeleteAndDeploy__c again (pathRepo: temp/manifest/package.xml )
7. use command:
sfdx force:source:deploy --manifest temp/manifest/package.xml --predestructivechanges temp/destructiveChangesPre/destructiveChangesPre.xml  --apiversion 53.0 --targetusername MyOrg --ignorewarnings  --wait 30
8. Check if object exist (it should, but it doesn't)

### Expected result

Object should exist!  because BEFORE deploy we deleting object and we deploy it again!

### Actual result

Object is NOT exist 

### System Information

![screen](https://user-images.githubusercontent.com/93764155/144221065-a3c80a01-188f-40f0-89f3-32bf62abf2a9.png)

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
I have questions about this
1. why are you deleting then deploying the same object?  Is it because the object had children (ex: list views) that you don't want to keep around, but just deploying it doesn't delete those children?
2. did this work some way before the CLI added this feature (for example, you were doing this using the ANT tool where the object was named in the destructive (pre) manifest and then also deployed in `package.xml`)

I'm pretty sure I understand why this doesn't work but am trying to figure out if it should and what the use cases might be that would prioritize this change

**Comment by mshanemc** [comment]
it's a great repro!
