### ISSUE TITLE
SFDX Cli doesn't recognise aura components nested under the aura folder

### ISSUE THREAD

**Issue by steals** [forcedotcom/cli#1358]
### Summary

In our project we organised metadata components in the sub folders. For example `Abstract Classes`, `Helpers` are sub folders under `classes` folder. `Base Components`, `Service Components` are subfolder under `aura` folder. Everything worked like a charm before the `plugin-source` was integrated into the cli in version ~7.112. Starting from that version and till now (ver 7.133) if we try to deploy some aura component that is placed in the subfolder (i.e. `force-app/main/default/aura/Quick Actions/Super Action`  with `sfdx force:source:deploy -x manifest/package.xml` command we receive `... AuraDefinitionBundle was named in package.xml, but was not found in zipped directory` or `No source-backed components present in the package.` error.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-nested-aura-issue](https://github.com/steals/sfdx-nested-aura-issue)

1.  Clone the repository
1.  Create a default scratch org `sfdx force:org:create -f config/project-scratch-def.json --durationdays 1`
1.  Try to deploy source to scratch org `sfdx force:source:deploy -x manifest/package.xml `

### Expected result

All Aura components are deployed even they are placed in the subfolder under `aura`

### Actual result

`No source-backed components present in the package.` is thrown.

### System Information

```
{
        "cliVersion": "sfdx-cli/7.133.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@muenzpraeger/sfdx-plugin 0.5.0",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-mobile 1.4.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdmu 4.12.3",
                "sfdx-cli 7.133.0 (core)",
                "source 1.7.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.3.0"
}
```

**Comment by maggiben** [comment]
Hi @steals prior to that version we used a less strict version of the source deploy mechanism, that allowed developers to make things like nesting code, which is a bad code practice and really never supported by salesforce, this had the consequence of creating bad salesforce development habits like nesting code.
Last year we introduced a new library called SDR that is more performant and robust but also more strict about where developers place their code, you're not the first user to report this problem, unfortunately there is no way for the new library to go back being as permissive as the old one was because that would break many things, we encourage developers to stay away from nesting components under any type of folder not just aura, Im sorry I can't give you any more help.
