### ISSUE TITLE
Silent installation of Salesforce CLI

### ISSUE THREAD

**Issue by anique9999** [forcedotcom/cli#1371]
Can please tell how can I install/uninstall 'Salesforce CLI' silently?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10462376](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000gxDfXYAU/view)

**Comment by cristiand391** [comment]
Hey, sorry for the late reply, we are triaging old issues and found this.

What do you mean by "silent installation"?

**Comment by dazzur** [comment]
Typically Windows executables use an installer program that wraps the .EXE file with other information about the file. Part of that other information is command line parameters to instruct the executable to install / unistall itself without any user intervention. The standard parameter to install this is to use "-s" for a "silent" install and "-u" for a silent uninstall. 

Typically other command line parameters are also provided to allow the executable to be installed in a particular location, or provide information that would otherwise be provided by the user doing an install, or be given a specific Application Name or Icon, or run a post-install action, etc. 

InstallShield (https://www.revenera.com/install/products/installshield) is a popular installer, as well as Actual Installer for free (https://www.actualinstaller.com/) ... but there are others. 

Silent installs (and uninstalls) are really important for MDM (Managed Device) installations - so, if I want to install SFDX on all our corporate devices I would be able to create an instruction file for that which includes the command line parameters needed for a silent (no user interaction) install / uninstall, which I could deploy from a central cloud managed solution.

**Comment by dazzur** [comment]
Actually, I just noticed that you use Nullsoft installer - so refer to this - https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon

**Comment by mshanemc** [comment]
yeah, what @dazzur said.  See if `/S` after the exe file makes it silent?
