### ISSUE TITLE
org create fails if ancestorVersion = HIGHEST

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1453]
### Summary

`ERROR running force:org:create:  The ancestor versionNumber must be in the format major.minor.patch but the value found is HIGHEST`

DX Documentation strongly recommends using the keyword HIGHEST for the ancestorVersion. However, when doing so, scratch org creation fails saying the value is invalid.

When creating a scratch org, why does ancestor version even matter? As-is, the recommended config is not usable.

### Steps To Reproduce:

1. Have a 2GP managed package
1. Set `"ancestorVersion": "HIGHEST",` for the package in sfdx-project.json
1. Attempt to create a new scratch org

### Expected result

Scratch org gets created

### Actual result

`ERROR running force:org:create:  The ancestor versionNumber must be in the format major.minor.patch but the value found is HIGHEST`

### System Information

sfdx-cli/7.142.1 linux-x64 node-v16.14.0
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.2.1 (core)
apex 0.11.0 (core)
auth 1.8.1 (core)
community 1.1.4 (core)
config 1.3.23 (core)
custom-metadata 1.0.12 (core)
data 0.6.9 (core)
generator 1.2.2 (core)
info 1.3.0 (core)
limits 1.3.0 (core)
org 1.11.2 (core)
salesforce-alm 54.0.1 (core)
schema 1.1.0 (core)
sfdx-cli 7.142.1 (core)
source 1.8.18 (core)
telemetry 1.4.0 (core)
templates 54.2.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)

**Comment by WillieRuemmele** [comment]
Hi @yippie could you provide an example `sfdx-project.json` we could use to test with? Have you tried it with the `org:beta:create` command?

**Comment by bbrummer** [comment]
Same issue here, it's just broken.  But thanks "no-response" bot for your fantastic assistance.  This issue is trivial to reproduce, the "force:org:create" code just plain doesn't grok "HIGHEST".  The idea that you need a sample sfdc-project.json to proceed is absurd: This clearly wasn't tested or even implemented.

I really, _really_ wish none of these shenanigans were tracked in sfdc-project.json at all.  Doing so forces real development (that uses CI/CD and _gasp_ multiple developers) to completely kludge the hell out of the process by auto-generating the file on the fly because the project's source tree is an absolutely ridiculous place to try and manage build and package history.

**ERROR running force:org:create:  The ancestor versionNumber must be in the format major.minor.patch but the value found is HIGHEST**

{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "my_package",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "ancestorVersion" : "HIGHEST"
        }
    ],
    "namespace": "MYNAMESPACE",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "51.0",
    "packageAliases": {
        "my_package": "0HoXXXXXXXXXXXXX"
    }
}

**Comment by shetzel** [comment]
@bbrummer - same issue as reported in https://github.com/forcedotcom/cli/issues/1392. See that issue for more details.  The fix should be in the current CLI release candidate scheduled for promotion tomorrow.

**Comment by amil-abdallah** [comment]
As of today (FINALLY), I can confirm that I am able to use ancestor version HIGHEST.

Today I ran the following commands from terminal:

- npm update --global sfdx-cli
- sfdx update

My current SFDX version is now at: sfdx-cli/7.192.2 win32-x64 node-v18.14.1

Hopefully this is good news for other folks experiencing this issue still.
