### ISSUE TITLE
Safari support on Mac for `force:org:open -b`

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1461]
This is related to #1015 which added support for the `-b` flag to the `force:org:open` command. I recently integrated this into IC2--mapping the IDE's Web browser configuration to the flag used when invoking `force:org:open`--and was surprised to find no option for using Safari on Mac whereas there was an option to use Edge on Mac (which I confirmed to work). Is that just a limitation of the underlying library used to launch the specific browser? It seems like Safari should be an option on Mac since it's the OS's default browser.

**Comment by WillieRuemmele** [comment]
Hi Scott 👋 

it seems like it might be an issue in the [open](https://github.com/sindresorhus/open#app) library we use. It has a detailed explanation for cross-platform browser names and how to support it. After some more reading it seems like safari isn't supported... which makes the next paragraph even weirder

it's also weird because in the QA of that PR, Shane mentions `-b safari` opening [both chrome and safari](https://github.com/salesforcecli/plugin-org/pull/100#issuecomment-849919687)

**Comment by SCWells72** [comment]
@WillieRuemmele, yeah, I figured if it was an oversight it would have been addressed by now. I searched existing issues and didn't see anything for this, though, so I thought I might as well log one myself just in case. If the resolution of this is effectively "not supported by the underlying library", you can feel free to close it that way. Otherwise if you want to leave it out there or even link it to any associated logged issue in the underlying lib, that's fine as well. Thanks for providing the status!
