### ISSUE TITLE
mdapi deploy/retrieve client timeout error

### ISSUE THREAD

**Issue by adammyhre** [forcedotcom/cli#1511]
### Summary

After updating to v7.150.0, using mdapi deploy and retrieve commands are failing with an error message 
'Metadata API request failed: The client has timed out.'

Issue happens regardless of using SOAP or REST.

### Steps To Reproduce:

1. ant clean src:compile
2. sfdx force:mdapi:deploy --verbose --deploydir builddir --wait -1 -u alias

### Expected result

The package should be retrieved / deployed.

### Actual result

ERROR running force:mdapi:deploy:  Metadata API request failed: The client has timed out.

#### Verbose logging gives:

```
2022-05-13T14:43:01.613Z sfdx:Deploy INFO *** Deploying with SOAP ***
ERROR running force:mdapi:deploy:  Converting circular structure to JSON
    --> starting at object with constructor 'Connection'
    |     property 'analytics' -> object with constructor 'Analytics'
    --- property '_conn' closes the circle
*** Internal Diagnostic ***

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Connection'
    |     property 'analytics' -> object with constructor 'Analytics'
    --- property '_conn' closes the circle
    at JSON.stringify (<anonymous>)
    at C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:688:29
    at Array.map (<anonymous>)
    at _filter (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:677:17)
    at C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:141:37
    at C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:605:61
    at Array.forEach (<anonymous>)
    at Logger.applyFilters (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:605:33)
    at Logger.debug (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\logger.js:503:32)
    at Deploy.deploy (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\plugin-source\lib\commands\force\mdapi\deploy.js:60:21)
Outer stack:
    at Function.wrap (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\core\lib\sfdxError.js:171:27)
    at Deploy.catch (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\command\lib\sfdxCommand.js:248:67)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Deploy._run (C:\PROGRA~1\sfdx\client\node_modules\@salesforce\command\lib\sfdxCommand.js:85:13)
    at async Config.runCommand (C:\PROGRA~1\sfdx\client\node_modules\@oclif\config\lib\config.js:173:24)
    at async SfdxMain.run (C:\PROGRA~1\sfdx\client\node_modules\@oclif\command\lib\main.js:27:9)
    at async SfdxMain._run (C:\PROGRA~1\sfdx\client\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\PROGRA~1\sfdx\client\dist\cli.js:162:47)
******
```

### System Information

```
sfdx-cli/7.150.0 win32-x64 node-v16.15.0

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.11.0 (core)
auth 2.0.2 (core)
community 1.1.4 (core)
config 1.4.6 (core)
custom-metadata 1.1.0 (core)
data 0.6.15 (core)
generator 2.0.0 (core)
info 2.0.0 (core)
limits 2.0.0 (core)
org 1.12.1 (core)
salesforce-alm 54.3.0 (core)
schema 2.1.0 (core)
sfdx-cli 7.150.0 (core)
signups 1.0.0 (core)
source 1.9.7 (core)
telemetry 1.4.0 (core)
templates 54.6.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)
```

### Additional information

- Downgrading to v7.149.1 solves the issue.
- Using `sfdx force:mdapi:legacy:deploy` solves the issue.

**Comment by adammyhre** [comment]
Changing `wait` to a greater value also solves the issue.  IE: `-w 300`

**Comment by alan-morey** [comment]
I wonder has parity between the new and the legacy `mdapi` commands changed with regards to allowable values for the `--wait` flag?

Previously the `mdapi` commands would allow passing `-1` as the timeout value for `--wait` and this would make the command wait indefinitely. I found this more convenient, rather than providing some arbitrarily large value for timeout.

**Comment by alan-morey** [comment]
Inline help shows `--wait` flag with default value `[object Object]`, I would have expected integer value here. It seems the help description text for `--wait` also has 2 defaults, one in square brackets and one in parentheses.
 
```
 -w, --wait=wait
      [default: [object Object]] wait time for command to finish in minutes
      (default: 0)
```

The [documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_mdapi.htm#cli_reference_force_mdapi_beta_deploy) is a little confusing, is the default 0 or is the default -1?


```
-w | --wait WAIT
Optional
The number of minutes to wait for the command to complete. The default is –1 (no limit). 0

Type: minutes
Default value: 0 minutes
```

**Comment by SoftCreatR** [comment]
While the documentation is a little bit confusing here, the correct value for infinite time is `-1`.

**Comment by mshanemc** [comment]
the correct value for an infinite timeout is `-1`.

BUT...there's a bug in this that's being tracked as https://github.com/forcedotcom/cli/issues/1519

**Comment by gael-Cangy** [comment]
Hello I had the same issue running the following commands:

- sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings -w 100
- sfdx force:mdapi:deploy -d destroy --ignorewarnings -w 100

When I tried with: 
- sfdx force:mdapi:legacy:deploy -d destructiveChanges --ignorewarnings -w 100

 which is using the "legacy" argument it works perfectly fine in our CDCI pipelines.
 
== OUR SFDX VERSION ==
`
+ sfdx --version
sfdx-cli/7.150.0 linux-x64 node-v16.15.0
`


== OUR SFDX PLUGINS VERSIONS ==
`
+ sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.11.0 (core)
auth 2.0.2 (core)
community 1.1.4 (core)
config 1.4.6 (core)
custom-metadata 1.1.0 (core)
data 0.6.15 (core)
generator 2.0.0 (core)
info 2.0.0 (core)
limits 2.0.0 (core)
org 1.12.1 (core)
salesforce-alm 54.3.0 (core)
schema 2.1.0 (core)
sfdx-cli 7.150.0 (core)
signups 1.0.0 (core)
source 1.9.7 (core)
telemetry 1.4.0 (core)
templates 54.6.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)
`

Do you think changing the --wait time to a higher value work? since we are already using 100 here.

**Comment by iowillhoit** [comment]
👋 The `--wait -1` (`-w -1`) bug has been fixed in latest-rc version `7.151.1`. This will be promoted to latest tomorrow (Thursday). The help docs have also been updated to make this functionality more clear.

• Update with npm: npm install -g sfdx-cli@latest-rc
• Update with Installer: sfdx update stable-rc (run sfdx update stable to rollback)

Please let us know if you continue to have issues. Thanks for everyone's patience while it got this fixed!

**Comment by iowillhoit** [comment]
Hello again, `sfdx` version `7.151.1` has been promoted to latest! This should fix all of the `--wait -1` issues. The flag help has also been corrected. If you are still having issues please open a new ticket with steps to reproduce. Thanks!

Note that we are still seeing some performance degradation with deploys to sandboxes https://github.com/forcedotcom/cli/issues/1522

**Comment by faheemaligit** [comment]
I am using sfdx version 7.151.1 and still it's throwing the same error again and again, can anybody help?

the error is thrown when I am trying to retrieve

![image](https://user-images.githubusercontent.com/85924785/185120057-3dbc5d6c-ea73-467c-a645-4929dee65e3b.png)
