### ISSUE TITLE
If CMS channel for workspace is not created and a content type route exists, do not fail a `sfdx force:source:push`

### ISSUE THREAD

**Issue by leslchan** [forcedotcom/cli#1552]
**Is your feature request related to a problem? Please describe.**
I’m also trying to get around the `sfdx force:source:push` failure due to requiring a CMS to be connected because the existence of a CMS content type route.  The error is:

```
Content Detail pages host Salesforce CMS content. If you want content on the ShopVestas1/views/newsDetail.json, add this site as a Salesforce CMS Channel.
```

Currently there is no way to create the CMS via tooling or API calls, so when the scratch org is created, it is already "inconsistent", causing errors during the code push.

Can the SFDX tool warn about the CMS needed but not fail?  

**What are you trying to do**
After creation on a scratch org that has a CMS content type route, push code to the scratch org without a force push.

**Describe the solution you'd like**
Throw a warning if the CMS is not available, but allow pushing of code.  Would like all the other normal errors to show up, so a solution like force push will hide all the good errors.

**Describe alternatives you've considered**
- Force push the code, but that will hide all the good errors.  
- Manually recreate the CMS after the creation of a scratch org. Or use some automated tool to manually click through the UI to do so.

**Additional context**

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11216432](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xymedYAA/view)

**Comment by leslchan** [comment]
Turns out I can ignore the warning with:
```
> sfdx force:source:push --ignorewarnings
or
> sfdx force:source:push -g
```
This issue is resolved for me and the work item can be closed.

**Comment by joneychow-intertek** [comment]
Is there any update on this topic?

I experience the same issue when deploying into a scratch org with **sfdx force:mdapi:deploy** via a CI/CD pipeline

I could temporarily use the ignorewarnings flag to pass the scratch org validation.
However, I am taking a risk ignoring other potentially important warning message if going this route.

Will there be a proper solution allowing the CMS to be created via API and managed in a git repository?
I have no visibility on the [W-11216432](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xymedYAA/view), not sure what will be the solution

Will be really appreciated if somebody can shed some light on this topic. Thank You

**Comment by peternhale** [comment]
@joneychow-intertek this issue was closed when original reporter accepted the workaround for their situation. The ticket [W-11216432](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xymedYAA/view) was also closed as something we would not fix in the push command, given the lack of API support to do the necessary action on the server side to create the CMS, the suggested solution of skipping the warning for this case seems like a snowflake to me to include in the push logic.

I understand your frustration with this issue, so I will discuss our internal ticket with my team to see if there might be an alternative that would be good for you and the product. The discussion cannot occur before next week, given the holiday this week.

**Comment by RodEsp** [comment]
Hey @joneychow-intertek, we discussed this internally and decided it's not something that the CLI can realistically support without API support. We appreciate your feedback but ultimately the solution for this has to go through a different team. If this is a critical issue for your organization please contact Salesforce Customer Support.

**Comment by joneychow-intertek** [comment]
Thanks @peternhale and @RodEsp looking into this issue.

Understood this issue is out of your team's control without an API support. After a few more research, seems like a change is coming. Refer to the conversation in the link below.

https://salesforce.stackexchange.com/questions/328118/is-it-possible-to-create-a-cms-workspace-using-api-or-with-metadata-deploy
