### ISSUE TITLE
sf login functions jwt: TypeError: Cannot read properties of undefined (reading 'token')

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1594]
I'm able to login to my org using `sf login org jwt -a vdallano -i CLIENT_ID -f ../jwt/server.key -l https://test.salesforce.com -u USERNAME --json`, but when I try `sf login functions jwt -a vdallano -i CLIENT_ID -f ../jwt/server.key -l https://test.salesforce.com -u USERNAME --json` I get the following error `TypeError: Cannot read properties of undefined (reading 'token')`

![image](https://user-images.githubusercontent.com/55927613/175989585-0af992d4-5286-433c-9423-c884b173d099.png)

![image](https://user-images.githubusercontent.com/55927613/175990034-4ace3065-1e6d-4644-9359-c6f2c0e8cdc6.png)

I just changed the word `org` to `functions` and hit enter. So what could be the problem?

I tried to update sf to the latest version but it didn't work
![image](https://user-images.githubusercontent.com/55927613/175992707-dc812aef-f7c9-48b0-8090-974a2cfe5d3a.png)

**Comment by 0ptaq0** [comment]
I am having the same issue on Jenkins slave - Debian:
`@salesforce/cli/1.34.0 linux-x64 node-v16.15.1`
While locally it works fine.

**Comment by pgajek2** [comment]
Hi, the same problem here. Could you help?

**Comment by AllanOricil** [comment]
It only works with Prod orgs that have functions enabled. You both probably tried to login with a sandbox. As per doc, this seems to be working as designed.

**Comment by 0ptaq0** [comment]
The creds were for Production. The issue was that I was trying to log in to org and functions with an API-only user. 
**WORKAROUND**: But it requires standard UI login for the first time to accept the Functions access terms. 
After one-time UI login, I was able to do that with jwt.
I guess it is a corner case to be covered by Salesforce.

I have described this issue and some others which I came across during implementing Salesforce Functions in CICD here - https://beyondthecloud.dev/blog/salesforce-functions-in-cicd
Hope it helps
