### ISSUE TITLE
BUG/QUESTION : sfdx force:user:password:generate -u myusername is saying --targetdevhubusername flag will be deprecated

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#1618]
### Summary

The command `sfdx force:user:password:generate -u myusername` is saying that the `--targetdevhubusername` flag will be deprecated in v57 or later.

How strange. Why ?

### Steps To Reproduce:

I have created a new scratch org with Cumulus CI and org settings which were not successfully pushed, which produces this error message :
`ERROR running force:org:create:  A scratch org was created with username test-vaantfan6lq7@example.com, but the settings failed to deploy 
`
so this scratch org username is not set as default.

### Expected result

In this situation, I would not like to have to set the org as default before having to generate the password, if the '-u username' flage was deprecated.

**Comment by cristiand391** [comment]
Hi @RupertBarrow the deprecation warning only applies for the `--targetdevhubusername/-v` flag, the `--targetusername/-u` flag should be working and we aren't planning to remove it or any other big change in the `user` commands.

### Why are we deprecating the target devhub flag?
[During QA ](https://github.com/salesforcecli/plugin-user/pull/319#issuecomment-1129415726)we found some `user` commands never used this flag (seems it was accidentally enabled when open sourcing these commands), we added this warning so that people remove this flag from their scripts before we completely remove it (after that sfdx will throw exit code when passing that flag).

Commands affected:

- `force:user:list`
- `force:user:password:generate`
- `force:user:display`

**Comment by RupertBarrow** [comment]
What do you think about my use-case ?

I create a scratch org; this command fails partially, so the scratch org is created but I get an error message, and the scratch org user is not set as default user.

**Comment by cristiand391** [comment]
In the use-case you specified the scratch org was created but sfdx failed to deploy the settings, do you deploy the settings manually?

sfdx could catch that specific error and set the org as default, but that will be only one case where the org creation may fail, see: https://developer.salesforce.com/blogs/2022/07/better-manage-scratch-org-creation-using-the-env-create-scratch-command-beta

**Comment by mshanemc** [comment]
>What do you think about my use-case ?
>
>I create a scratch org; this command fails partially, so the scratch org is created but I get an error message, >and the scratch org user is not set as default user.

then you can use -u with the username of the partially failed scratch org.  Or use `config:set defaultusername=[your org's username]` to make it the default like you wanted.

**Comment by RupertBarrow** [comment]
Thanks Shane, I use the '-u' option.
When I use that, it's telling me that it will be obsolete in v57.

Just saying. Not important. If necessary, we can use the "set defaultusername" command, but it's a pity to have to memorize another command when '-u' is easy.

**Comment by mshanemc** [comment]
it is **definitely not** saying -u will be obsolete. 

it is warning every user of the command (regardless of which flags they use) that `-v  | --targetdevhubusername` will be obsolete.

I'm trying to figure out if the confusion is because of the similarity between `targertusername` and `targetDEVHUBusername` or because `u` and `v` are pretty similar.

Or maybe you're expecting it to only warn users if they use the `-v  | --targetdevhubusername` in their command, and so you think the warning applies to what you just entered and don't notice the subtle difference?

Whatever it is, it sounds like a usability issue.
