### ISSUE TITLE
7.172.0 and Cannot set sharingModel to ControlledByParent

### ISSUE THREAD

**Issue by dcano421** [forcedotcom/cli#1760]
### Summary

We get the following error when using 7.172.0 to install an unlocked package into a sandbox. 
Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field

### Steps To Reproduce:

1.  Just try to install an unlocked package into a sandbox that has any custom child objects with a Master-Detail relationship with the custom parent object and is set to ControlledByParent.

### Expected result

Should install successfully, like it does with previous versions. 

### Actual result

Fails on above error. Stated again, below:
Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field

### System Information

sfdx-cli/7.172.0 linux-x64 node-v16.17.1

**Comment by agentgill** [comment]
Additional Info - I've started getting this on new org-dependent packages for objects which have not changed in the package. Started post Winter 23 (this weekend)

Version - sfdx-cli/7.173.0 darwin-arm64 node-v16.17.0
Also tested 7.172.0, 7.171.0

**Comment by WillieRuemmele** [comment]
Hi @agentgill @dcano421, It sounds like this is related to this weekend's Winter 23 release, I've let some internal packaging teams know so they can look into it. Also as a reminder, try out the `pacage:beta:*` commands too :)

**Comment by agentgill** [comment]
@WillieRuemmele, thanks William for responding. beta commands seem to be more stable and allowed me to get passed this issue.

**Comment by shetzel** [comment]
Reopening this as some customers have indicated that they cannot use the beta packaging commands in their CI scripts.  We'll leave this open until it's been fixed in the `force:package:install` command in the `salesforce-alm` plugin.

To be clear, this is working if the `force:package:beta:install` command is used from the `@salesforce/plugin-packaging` plugin, but not everyone is comfortable/allowed to use beta commands in their work flows.

**Comment by renatoliveira** [comment]
Started having this issue when creating a package version as well. The package creation fails because of the sharing model issue, and as such pretty much all classes and related objects also fail, leaving a trail of errors (almost 300) because of three objects that can't be created due to this issue.
