### ISSUE TITLE
"CLIError: timed out" Validation mdapi --checkonly with unit tests

### ISSUE THREAD

**Issue by matt-newell** [forcedotcom/cli#1899]
### Summary

_Running a validation --checkonly deploy successful to the org but CLI reports a timeout_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Exit code 0_.

### Actual result

_Exit code 1_.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
	- npm install -g sfdx-cli@latest-rc
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information
```
++ sfdx force:mdapi:deploy -d ./deploy -u OrgAlias9f365f4f0dda41a7b96f5b7f499f9140 -w -1 -c --concise -l RunLocalTests --json
++ jq -r ' .result.id'
CLIError: timed out
    at Object.error (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:1[24](https://github.com/VillageMD/salesforce/actions/runs/4008095348/jobs/6881817532#step:6:25):9) {
  oclif: { exit: 2 },
  code: undefined
}
+ local DEPLOY_JOB_ID=0Af7800000E02SSCAZ
```

The funny part is the deploy job id does return but the function exits code 1. 

_Feel free to attach a screenshot_.

<img width="1215" alt="Screenshot 2023-01-25 at 1 06 06 PM" src="https://user-images.githubusercontent.com/7570953/214646305-16c49026-0a98-4088-b964-e43c6a279fd8.png">

**Comment by shetzel** [comment]
If the deploy request times out, I'd expect a non-zero exit code so this is working as designed to me.  What is your CLI version?  `sfdx version --verbose`.  Recent versions of the CLI are more tolerant of conditions that cause timeouts.

Also note that rather than converting from source format to metadata-api format, then running a `force:mdapi:deploy` command you could run just `force:source:deploy`, which is also able to run a checkonly deploy.

Deploys and retrieves are asynchronous operations.  By using the `--wait` flag you are instructing the command to act synchronously.  I.e., start the deploy, then poll for results.  The deploy ID is returned by the initial request, then the timeout happens when polling for the results, so it's not strange that the response would have the deploy ID while still timing out.  This way, it's possible to use the deploy ID to continue checking the status if something goes wrong.

**Comment by matt-newell** [comment]
Actually I want the deploy / validation to be async. I have a second step that retrieves the deployment report as well as a failure report if that times out.

Thank You removing `-w -1` actually fixed the issue I was having
