### ISSUE TITLE
sfdx force:mdapi:deploy does nothing and passes succesfully

### ISSUE THREAD

**Issue by tony-tawk-ei** [forcedotcom/cli#1951]
### Summary

In our CD pipeline hosted on jenkins and bitbucket , we use the sfdx force:mdapi:deploy command to deploy a source to sandboxes.

Since today it just stopped deploying the code, and doesn't fail, just passes correctly doing nothing because we updated the installation command of sfdx in jenkins script in order to use the latest version (7.188.1) .

Why do we need to upgrade ? 

Because previously, we were installing the version 7.82.0 using the old tar.xz package via the url (https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz) on every build and this caused an error when trying to deploy the metadata type "PlatformEventSubscriberConfig".

### Steps To Reproduce:

    use sfdx force:source:convert command to create package
    then use sfdx force:mdapi:deploy to deploy

### Expected result

      The latest changes from the package are deployed to the org.

### Actual result

     Nothing happens, deployment is not shown even on sandbox under the deployment tab, pipeline passes this step correctly and moves forward and the number of deployed components is 0 for any type of metadataype component.

### System Information

- The jenkins server is deployed on an ubuntu machine , and the issue is present if we install sfdx using sudo npm install sfdx-cli --global or the method described [here ](https://developer.salesforce.com/docs/atlas.en-us.222.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm)

- the sfdx version :  sfdx-cli/7.188.1 linux-x46 node-v18.13.0

### Additional information

As a temporary solution, we are using the tar package that installs the the version 7.82.0 because it is able to deploy all components types except "PlatformEventSubscriberConfig".

But we need to upgrade to the latest version of sfdx in our automated script to avoid any future issue with new types of components.

![Screenshot 2023-02-21 083223](https://user-images.githubusercontent.com/49707818/220265529-165418f5-58da-4147-947a-8cd22025b593.png)

**Comment by mshanemc** [comment]
@tony-tawk-ei 

1. If you've got a way to reproduce that `mdapi:deploy` error, I'd like to get it because that's definitely a bug.  Most of the times we've seen these before, there's some "wrong" metadata structure (file extensions, or folders/components where they don't belong).  Older versions tolerated that, or sometimes skipped the file, but the updated one won't.  [The CLI needs to give you a better error about where the problem is, which is why I'm interested in a repro]
2. On CLIs from the last few years, you don't have to convert to mdapi to deploy.  You can `force:source:deploy` and then specify what you want.  It'll save a LOT of time both locally and in CI.  There's also a chance that'll tell you where the error is where the `mdapi` command is just exiting.

**Comment by tony-tawk-ei** [comment]
Hello , 

  I finally removed the conversions to mdapi and replaced force:mdapi:deploy with force:source:deploy .

 Everything is working as expected with the latest version of sfdx.

 It wasn't easy. It took 2 days to change and test this in my CI/CD flow , don't change your mind next year and don't get back to mdapi. :)

Thank you.

**Comment by tony-tawk-ei** [comment]
.
