### ISSUE TITLE
source deploy report - fire postdeploy hook

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/cli#1989]
**Is your feature request related to a problem? Please describe.**
No.

**What are you trying to do**
Typically we split our deployments into a short call of force:source:deploy (with wait of 0) and then use force:source:deploy:report (with the job id). Ideally it would be nice if the postdeploy hook fired when the force:source:deploy:report deals with a done=true deployment result.

**Describe the solution you'd like**
Post deploy hooks fire when force:source:deploy:report receives a done deployment result.

**Describe alternatives you've considered**
Creating a custom source:deploy:report command (in the same plugin that contains the hooks) that calls the postdeploy hook on a done deployment result - the current work-around if we want to use hooks. The other option is to call the post deploy logic manually.

**Additional context**

**Comment by iowillhoit** [comment]
Hey @gitfish, I want to confirm I understand the request. 
- You are running `force:source:deploy` with `--wait 0` to run the deploy async
- You then run `force:source:deploy:report` with the `id` to get the status
- Once the status is `done=true` you'd like for the post deploy hook to fire? 

If so, I don't know of a way that we could prevent the post deploy hook from firing over and over. 
For example if you accidentally ran `sfdx force source deploy report --jobid SOME_STALE_ID` two days after the deploy completed, the status would still equal `done=true` and would fire the deploy hook again. 

I think you may be better off with the alternative that you suggested, write a function to poll the status until it is finished and manually run the post deploy logic.

**Comment by gitfish** [comment]
Hi @iowillhoit - yep, probably the only way is with a flag indicating that you'd like to fire hooks.

**Comment by iowillhoit** [comment]
Ok, I spoke with a teammate on this. This is not something that we are planning on bringing to `force source deploy report`. However, we are in the process of bringing in [plugin-deploy-retrieve](https://github.com/salesforcecli/plugin-deploy-retrieve) from `sf`. The `project deploy resume` command should give you the functionality you are looking for. 

Please note that some of these beta commands will be changing names prior to coming over. I believe it will be called `project deploy resume` by the time it ships. Here is the [reference guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_deploy_commands_unified.htm#cli_reference_deploy_metadata_resume_unified) if you are curious. 

Let me know if you have any more questions, otherwise feel free to close this issue. Thanks @gitfish

**Comment by gitfish** [comment]
Cool - thanks for the info.
