### ISSUE TITLE
upsert 300mb file sfdx-cli  7.193.2  

### ISSUE THREAD

**Issue by mlavind** [forcedotcom/cli#2084]
hi

We have a sfdx-cli  7.193.2  version.

The past months we have been upserting files larger than 150 mb and now it gives us an error. We know that saleforce has limited that but the cli let us do it.

We execute this --> 
sfdx data upsert bulk -s Huella__c -f /home/salesforce/scripts/huella_MM_importar.csv -i Id_Domicilio_To__c --target-org preprod 

huella_MM_importar.csv is 273mb size. The last month goes ok but now we can import.

Someone help me?

**Comment by iowillhoit** [comment]
Hey @mlavind, sorry for the delayed response. Is this still an issue? Do you happen to know what version of `sfdx` that this started happening in? That would help narrow this down. Could you also share the error message that is displayed? I am going to attempt to reproduce the issue.

**Comment by iowillhoit** [comment]
Ok, I was able to replicate this. I am going to get a repo put together for easy reproduction of the issue and we'll get it looked at. Thanks for reporting this 👍

**Comment by iowillhoit** [comment]
Repo with instructions: https://github.com/iowillhoit/bulk-upsert-repro

**Comment by WillieRuemmele** [comment]
Hi @mlavind -

while we are in the process of removing the `force:` from most commands, the `force:data:bulk:*` commands are an exception because they continue to use the Bulk API 1.0, while the newer `data:bulk:*` commands have been switched to use the Bulk API 2.0  - this is why you're seeing the different results for the different commands

we're talking about how/if it is possible to support the Bulk API 1.0 for cases like this... until then, if you revert back to the `force:data:bulk:*` commands, you'll be able to upload more than the 150 mb limit

**Comment by mlavind** [comment]
Thank you i go to view that you say. Thanks a los of!!!!

**Comment by WillieRuemmele** [comment]
Hi @mlavind - I put up a PR to add this feature, but then as a team, we decided we'd do this work in a hollistic way once we add more commands to the `data` plugin. This will allow us to create a unified and consistent command structure and behavior. We'll be moving the batching functionality into the underlying `jsforce` library, and exposing it through the CLI
