### ISSUE TITLE
latest SFDX command warning issue SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.

### ISSUE THREAD

**Issue by adityasfdev** [forcedotcom/cli#2106]
(node:2329) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2329) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.

im getting the above warning while running the latest SFDX Commands in my pipeline which is running under the agent "ubuntu" should i be worried about this waring or i need to set any environment variables while running the command in the pipeline? please help me to resolve this issue.

**Comment by mshanemc** [comment]
Do you have that env (`SFDX_AUTOUPDATE_DISABLE`) set in your CI environment?  If so, you can update it like the warning says to avoid seeing the warning.

If you don't set that env, I'd be really interested in where it's coming from (and what version of the CLI your CI is using) because we removed all our uses of it.  https://github.com/search?q=org%3Asalesforcecli+SFDX_AUTOUPDATE_DISABLE++NOT+is%3Aarchived&type=code

**Comment by adityasfdev** [comment]
Hi @mshanemc nope i didn't set any environment variables im just installing the latest CLI using this command "npm install --global sfdx-cli@latest-rc " after runnning this installation command in my CI CD pipeline im running the jwt login and project deploy start command so when im running those command im seeing this warning in my CI CD pipeline even though i didn't set any environmental variables. 

And im using SFDX not SF in my commands and its running ubuntu OS.

**Comment by mshanemc** [comment]
I'm not able to replicate this with what's in RC right now `sfdx-cli/7.199.7 darwin-x64 node-v18.13.0`.

We did recently add the warnings about old envs, so I'm 100% sure this is coming to that change, but I can't figure out how you got to it since *no CLI code refers to that variable anymore*.

I do see various other people's code on github that sets it.  Maybe your CI or a plugin uses the env?  https://github.com/search?q=SFDX_AUTOUPDATE_DISABLE&type=code

**Comment by adityasfdev** [comment]
In my CI CD pipeline i have two set of stages one for QA validation and another one for UAT Validation 

In QA we did added a plugin for to scan the lwc apex and aure code the plugin is Salesforce code analyzer this is the installation command which im using -->  "sfdx plugins:install @salesforce/sfdx-scanner" and we are running the scanner command to scan the code --> "sfdx scanner:run --target "**/classes/**" " and after this step we are running the Jwt login and deployment command so in that stage only where we running the sfdx scanner plugin there we getting this warning which i mentioned in the earlier command

In UAT validation where we didn't added the sfdx scanner plugin there is no warning showing for the sfdx commands.

so the issue is with where im running sfdx scanner plugin command 
sorry for not telling you the issue properly at start.

**Comment by mshanemc** [comment]
I didn't find anywhere in scanner, either, that uses that env.

I think this should go away when you update your CLI.  It's a warning you can ignore if you're not setting the env or depending on it being set.

**Comment by adityasfdev** [comment]
im using the latest cli only in CI CD pipeline but yeah lets see it''ll go away in future or not and thanks for your help in this issue and has you mentioned ill ignore this warning for now

**Comment by supert3d** [comment]
I get the same when trying to use APEX Debugger - [Github Issue 2232](https://github.com/forcedotcom/salesforcedx-vscode/issues/4927). I suspect it's due to the recent push to use SF in preference to SFDX and a lot of the existing node based toolsets haven't had code updated?

**Comment by NagarjunaParala** [comment]
(node:7284) Warning: Deprecated environment variable: SFDX_JSON_TO_STDOUT. Please use SF_JSON_TO_STDOUT instead.
(Use `node --trace-warnings ...` to show where the warning was created)
    TypeError: this.config.getPluginsList is not a function
