### ISSUE TITLE
project is not a sf command

### ISSUE THREAD

**Issue by thedavidhanks** [forcedotcom/cli#2185]
### Summary

Running `sf project deploy start` results in `Warning: project is not a sf command.`

### Steps To Reproduce:

run a sf command.  I get a similar result for: 
```~>sf deploy start --dry-run --target-org Preview --source-dir ./force-app/main/default -l RunLocalTests  --verbose
 »   Warning: deploy start is not a sf command.```

### Expected result

I expect my project to deploy to the org specified.

### Actual result

results in `Warning: project is not a sf command.`

### System Information

sfdx version
sfdx-cli/7.203.6 win32-x64 node-v18.15.0
sf --version
@salesforce/cli/0.0.38 win32-x64 node-v14.17.5

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
Same result in cmd.exe and git bash
cmd.exe --version => Microsoft Windows [Version 10.0.19045.2965]
bash --version => GNU bash, version 5.1.16(1)-release

**Comment by cristiand391** [comment]
@thedavidhanks you have an old version of `sf`:
`@salesforce/cli/0.0.38 win32-x64 node-v14.17.5`
latest sf is `1.80.6`.

See update instructions:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm

**Comment by thedavidhanks** [comment]
@cristiand391 
Do you have any other suggestions about how to update?  Where do you see 1.80.6 is the latest version?
The link you provided was for sfdx.  I've read that sf is supposed to be installed within this executable, but mine doesn't seem to have updated.

Neither the command `sfdx update`, nor [the installer](https://developer.salesforce.com/tools/sfdxcli) appear to have update the sf cli version.  I've also tried uninstalling and reinstalling.

**Comment by cristiand391** [comment]
@thedavidhanks I check on npm:
https://www.npmjs.com/package/@salesforce/cli

`@saleforce/cli` -> `sf`
`sfdx-cli` -> `sfdx`

I wonder if installed an early version of `sf` and that just got stuck in your system.

since you are using bash, can you run `which sf` to see where the `sf` executable is located? do you see it as a separate program in windows when trying to uninstall it?

**EDIT**:

for future reference, we also maintain this repo where you can see the status of the CLIs and libraries:
https://github.com/salesforcecli/status

you can see what the last version of the CLIs are in the **Package** column, next to each pkg name.

**Comment by thedavidhanks** [comment]
got it.

It appears I had installed both the npm package as well as the installer.  Therefore my PATH var was pointing to both versions.

running `npm uninstall @salesforce/cli`, then restarting the terminal resolved the issue.
