### ISSUE TITLE
sf project deploy report/cancel/resume doesn't support target-org

### ISSUE THREAD

**Issue by camisotro** [forcedotcom/cli#2421]
### Summary
If you compare the documentation of each of these SFDX commands with their sf equivalent:
`sf project deploy report` and `sf project deploy resume` with `force:source:deploy:report` 
`sf project deploy cancel` with `force:source:deploy:cancel`
You will see that the sfdx-style commands support a `-u` / `--targetusername` flag. However the sf-style commands do not contain the `-o` / `--target-org` flag in their documentation. Rather confusingly, the section of the sfdx documentation about switching to the sf-style commands **does** suggest that the sf commands support `-o`. However this does not actually work. 

### Steps To Reproduce
Try to check a deployment job ID in an org while specifying target org.
e.g. `sf project deploy report --job-id 0AfDH00001mIItQ -o myOrg`

I get the error: `Error (1): Nonexistent flag: -o`.

### Expected result
`sf project deploy report` and similar commands should have a documented target-org flag for feature parity with the sfdx commands.

### Actual result
`sf project deploy report` and similar commands do not have a documented target-org flag for feature parity with the sfdx commands. Attempting to use the `-o` flag leads to the error: `Error (1): Nonexistent flag: -o`.

### System Information
Powershell

```json
{
  "cliVersion": "@salesforce/cli/2.4.10",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\CharlesTroster\\AppData\\Local\\sf\\client\\2.4.10-703551c",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.16 (core)",
    "@oclif/plugin-not-found 2.3.36 (core)",
    "@oclif/plugin-plugins 3.2.0 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.30 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.4.10 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.5 (core)",
    "deploy-retrieve 1.17.2 (core)",
    "info 2.6.38 (core)",
    "limits 2.3.29 (core)",
    "login 1.2.25 (core)",
    "org 2.9.30 (core)",
    "schema 2.3.22 (core)",
    "settings 1.4.24 (core)",
    "sobject 0.2.2 (core)",
    "source 2.10.30 (core)",
    "telemetry 2.2.5 (core)",
    "templates 55.5.9 (core)",
    "trust 2.5.4 (core)",
    "user 2.3.28 (core)"
  ]
}
```

**Comment by cristiand391** [comment]
Hi @camisotro, in sf these commands are expected to be run after a deploy happened, which will save the org where the deployment happened.
When you pass a jobId, it will search in the cache for the deploy info (so it doesn't need `--target-org` because it's saved):
https://github.com/salesforcecli/plugin-deploy-retrieve/blob/212b7f2927fddc29ec26719825ae4acd84c24b82/src/commands/project/deploy/report.ts#L58-L61

As long as you run all the commands in the same machine this should work fine, but we are aware this doesn't work well if you are trying to pass the jobId from machine to another, see this discussion for possible solutions:
https://github.com/forcedotcom/cli/discussions/2300

**Comment by cristiand391** [comment]
> Rather confusingly, the section of the sfdx documentation about switching to the sf-style commands does suggest that the sf commands support -o. However this does not actually work.

I can't find that section about deploy commands: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_mig_deploy_retrieve.htm
can you share where do you see that so we can update it? thanks!

**Comment by camisotro** [comment]
@cristiand391 My expectation is that these commands should be capable of checking deployment job IDs that did not start on this machine. It's a more convenient tool than calling the API manually, and it's something that would come in handy in CI/CD contexts.

In regards to documentation, look here:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy_report
It explicitly tells you to switch to `project deploy report` but does so in a table that says the `force:source:deploy:report` flag `-u` maps to the `project deploy report` flag `-o`.

**Comment by cristiand391** [comment]
Thanks @camisotro , our tech writer will correct that table (could take a few days to show up).

Since we are tracking this feature request in https://github.com/forcedotcom/cli/discussions/2300, I'll close this issue for now.
Please let us know if you have any suggestion in the linked discussion (and also see the comment why this wouldn't work with `deploy resume`)
