### ISSUE TITLE
Org Shape Creation Failing with - The client has timed out

### ISSUE THREAD

**Issue by salesforcejourney** [forcedotcom/cli#2438]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I am planning to create scratch org using org shape feature. However scratch org creation failing with error - The client has timed out

### Steps To Reproduce

1) Created new Dev Org
2) Enable Dev hub and Org shape ( in my scenario both source org and dev hub org is same)
3) Maintain Dev Hub org Id in Org Shape.
4) Created org shape 
5) Modify config file and put source org as 

{
  "orgName": "Org Shape",
  "sourceOrg": "00D5j00000Cte7U"
}

Output

sfdx force:org:create -f config\project-scratch-def.json --setalias OrgShapeDemo --durationdays 1 --setdefaultusername --json --loglevel fatal
 ended with exit code 1

The client has timed out.
```
### Additional information
<!-- Feel free to attach a screenshot -->

**Comment by salesforcejourney** [comment]
Please find the version details

@salesforce/cli/2.5.8 win32-x64 node-v18.15.0

**Comment by shetzel** [comment]
This: `@salesforce/cli/2.5.8 win32-x64 node-v18.15.0` is the CLI version but it is also very helpful to know what the versions of the plugins are, which is why the issue template asks for the output of `sf version --verbose`.

My first suggestion is to use the new command for creating scratch orgs: `sf org create scratch`.  That alone could fix the issue for you.  If it still errors you can append `--dev-debug` and additional debugging output is displayed that can be helpful.

Next suggestion is to reference these docs: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_shape_scratch_def.htm
We are currently in a transition period so you may have to do some additional steps when creating scratch orgs from org shapes.
