### ISSUE TITLE
sf deploy metadata validate -l NoTestRun 

### ISSUE THREAD

**Issue by amanjareck** [forcedotcom/cli#2472]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by mcarvin8** [comment]
@amanjareck I submitted a similar issue via https://github.com/forcedotcom/cli/issues/2470

I was advised that by design, validate is a pre-cursor to quick-deploy and thus, enforces test coverage to run.

To "validate" without running any tests, use the `--dry-run` option on the `sf project deploy start` command and omit the test level to run a validation without tests. Salesforce will scan the package and set tests to Not Required when the package.xml doesn't contain Apex .

Something like this:
`sf project deploy start --dry-run -x manifest/package.xml --verbose`

**Comment by mshanemc** [comment]
I came here to say exactly what @mcarvin8 said.

**Comment by amanjareck** [comment]
Thanks a lot, and thanks for catching regardless of lack of explanation and a more verbose log. This is good, the command I am looking at is not well documented so have to go old school and use help in command prompt. Been fixing our pipelines and missed this one. 

Thanks once again guys :)
