### ISSUE TITLE
pre|post destructive deployment without a manifest

### ISSUE THREAD

**Issue by Karla-Dell** [forcedotcom/cli#2619]
### Discussed in https://github.com/forcedotcom/cli/discussions/2618

<div type='discussions-op-text'>

<sup>Originally posted by **Karla-Dell** December 22, 2023</sup>
Hello. We're trying to make use of pre-destructive-changes on the same deployment command, but we're facing errors. Apparently, that's only possible when a manifest is being used for the deployment and in our case, we're deploying from a directory. 
</br>
Example:
`$componentsDeployment = sf project deploy start --source-dir $folder --wait 1 --target-org TARGET_ORG --test-level NoTestRun --pre-destructive-changes ./preDestructiveChanges/destructiveChangesPre.xml --json | ConvertFrom-Json`
</br>
And this the the error we're getting:
"_All of the following must be provided when using --pre-destructive-changes: --manifest_"
</br>
Is this really expected? Shouldn't it work with directory based deployments as well?</div>

**Comment by cnwork** [comment]
We ran into the same roadblock. We are using a source directory for deploying **constructive** changes and would like to validate or deploy destructive ones at the same time. It's not possible due to this limitation.
Having to run the validation twice once for constructive and once for destructive is not just counterintuitive but also takes double the validation time with no actual benefit because after deploying the constructive changes we would need to run the validation again for the destructive ones. Can this option be added?
Another issue is that when we use manifest for deploying constructive changes, it deploys all child components which can greatly increase the time and the chances that things will not go right. If an option to disable child component deployment would be available, that could work as well.

**Comment by mshanemc** [comment]
closing.  We'll use the Discussion for feature requests
