### ISSUE TITLE
Invalid version specified:45.0

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/cli#27]
Deploy using Circle ci and getting an error with WInter 19 orgs.

sfdx force:config:set apiVersion=44.0 --global
sfdx force:source:convert -d deploy_prod -r force-app 
sfdx force:mdapi:deploy -u deployTarget -d deploy_prod/ -w -1 -l

**OS and version**:
![image](https://user-images.githubusercontent.com/93057/52307806-3c323280-2961-11e9-97f8-4af5159779fa.png)

![image](https://user-images.githubusercontent.com/93057/52308503-1c9c0980-2963-11e9-9f9a-6ce1bd7fded7.png)

**Comment by clairebianchi** [comment]
The API version you are seeing is actually either in your metadata or the package.xml that you are deploying, this is not caused by the CLI. 

What I believe happened is you pulled changes from an org that was on 45.0 (perhaps a scratch org) which updated the API version in your package.xml. This package then would not deploy because the org you are trying to deploy into is on the 44 version of the API. If you update the API version in the file it should work.

**Comment by chandra2ravi** [comment]
My pacakge.xml and metadata set to 44.0
![image](https://user-images.githubusercontent.com/93057/52347799-709d0180-29e8-11e9-9bc6-c26a0b870a99.png)
