### ISSUE TITLE
Dependencies have security vulnerabilities

### ISSUE THREAD

**Issue by hungrypipo** [forcedotcom/cli#2774]
For @salesforce/cli even the latest 2.34 version

Just one example, the ip module used 2.0.0 has a vulnerability that can be fixed by a higher version 

https://security.snyk.io/vuln/SNYK-JS-IP-6240864

 From npm-shrinkwrap.json:

 "node_modules/npm/node_modules/ip": {
      "version": "2.0.0",
      "inBundle": true,
      "license": "MIT"
    },

The other one that has a fix
https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607

**Comment by shetzel** [comment]
The many repos involved with building the Salesforce CLI have dependabot running weekly to keep everything as up to date as possible.  The `ip` module you referenced is currently at `2.0.0` and there is a recent patch release (`2.0.1`).  This dependency comes from a nested dep within `@oclif/plugin-plugins` so it would need to be bumped there and then the version of plugin-plugins bumped within the CLI.  I don't see `serialize-javascript` in use at all by the CLI.  But also, just because snyk reports a vulnerability doesn't mean it's a bug or vulnerability in a CLI environment (i.e., running locally on a machine).  How the library is being used is an important factor that tools like snyk don't consider.  Regardless, I'll look at the dependencies of `@oclif/plugin-plugins` but unless there's a bug involved with the CLI this is low priority and should eventually be handled by our dependabot update process.

**Comment by shetzel** [comment]
Will eventually be fixed with https://github.com/oclif/plugin-plugins/pull/821
