### ISSUE TITLE
Getting error: "Error (1): No results to format" when trying to get the entity data

### ISSUE THREAD

**Issue by rheacherian814** [forcedotcom/cli#2800]
https://confluence.internal.salesforce.com/display/PLATFORMDX/Adding+2GP+Managed+Packaging+metadata+channel+support

I'm following this doc to have my entity be supported for packaging, and I have registered the entity (AffinityScoreDefinition) to the CLI in this repo, but I'm still getting that error when I run these commands: 

sfdx force:mdapi:convert -r <FolderName> -d force-app/ 

which I believe should have resolved once my metadatype was registered (https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json). 

Can't find any information on slack about this, can anyone help?

**Comment by rheacherian814** [comment]
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.34.7",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 5.14.0-362.18.1.el9_3.x86_64",
  "rootPath": "/nix/store/5vxg9jzr8phqayd1rrl124mnc7xrpggp-sfdx-7.209.6",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.0 (core)",
    "@oclif/plugin-help 6.0.18 (core)",
    "@oclif/plugin-not-found 3.0.14 (core)",
    "@oclif/plugin-plugins 4.3.8 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.0 (core)",
    "@oclif/plugin-version 2.0.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.14 (core)",
    "@oclif/plugin-which 3.1.5 (core)",
    "@salesforce/cli 2.34.7 (core)",
    "apex 3.0.31 (core)",
    "auth 3.3.27 (core)",
    "data 3.1.11 (core)",
    "deploy-retrieve 3.2.35 (core)",
    "info 3.0.33 (core)",
    "limits 3.1.14 (core)",
    "marketplace 1.0.29 (core)",
    "org 3.5.0 (core)",
    "packaging 2.1.12 (core)",
    "schema 3.1.9 (core)",
    "settings 2.0.31 (core)",
    "sobject 1.1.20 (core)",
    "source 3.1.22 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.0.23 (core)",
    "trust 3.3.17 (core)",
    "user 3.3.4 (core)"
  ]
}

**Comment by cristiand391** [comment]
your type was included in SDR v10.7.0 (and a small fix about the suffix included in 10.7.1):
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/CHANGELOG.md#1071-2024-04-01

The CLI needs to use that SDR version (or higher) to recognize the type in your project.

> "deploy-retrieve 3.2.35 (core)",

the `force:mdapi:convert` command is part of the `deploy-retrieve` plugin, v3.2.35 is using SDR 10.5.3 so that explains why it doesn't work.

The available nightly has SDR v10.7.0 but it may not work because of the suffix fix, maybe wait for tomorrow to get the new nightly and try again?:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm

**Comment by rheacherian814** [comment]
Updating the nightly worked for me -- thank you!
