### ISSUE TITLE
Want to retrieve data using mdapi but getting error limit exceed

### ISSUE THREAD

**Issue by jeenamsuneja** [forcedotcom/cli#2846]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by jeenamsuneja** [comment]
System Information
Sfdx version: sfdx/7.8.1
Npm:8.1.0
Node js:16.13.0

**Comment by jeenamsuneja** [comment]
Error is 
"status": 1,
"result": {
"done": true,
"errorMessage": "LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000",
"errorStatusCode": "LIMIT_EXCEEDED" ,
"id": "0955000004¡e®EAA",
"status": "Failed",
"success": false,
"zipFile": {
"$"：｛
"xi:nil": "true"

**Comment by jeenamsuneja** [comment]
While retrieving the data using mdapi command getting the above error

**Comment by mshanemc** [comment]
The metadata API has a hard limit of 10,000 files in the retrieve.  You can split up your retrieve using manifests so that you stay under that limit.

---
### side notes: 
- node16 is EOL (by node) and no longer supported https://github.com/forcedotcom/cli/issues/1985
- that `sfdx` cli is ancient, like 5+ years old, and is not supported.  It's unsafe and you shouldn't use it.  
  - https://github.com/forcedotcom/cli/issues/2132
  - https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm
