### ISSUE TITLE
Signature for Community Plugin missing

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2848]
### Summary
Trying to JIT install community plugin in CI pipeline. I could use the [unsignedPluginAllowList](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm), however shouldn't all plugins under @salesforce/* be signed?

### Steps To Reproduce
1. Run `sf plugins install community` locally or in CI environment

### Expected result
@Salesforce/community installed successfully without prompting for signatures 

### Actual result
@Salesforce/community plugin install fails because it is unverified and shows verification prompt

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.39.6",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/user/.local/share/sf/client/2.39.6-6819d56",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.16 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.6 (core)",
    "@oclif/plugin-plugins 5.0.14 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.7 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.8 (core)",
    "@salesforce/cli 2.39.6 (core)",
    "@salesforce/commerce 250.1.0 (user)",
    "apex 3.1.9 (core)",
    "auth 3.6.3 (core)",
    "community 3.2.6 (user)",
    "data 3.3.2 (core)",
    "deploy-retrieve 3.6.6 (core)",
    "info 3.2.3 (core)",
    "limits 3.3.4 (core)",
    "marketplace 1.2.4 (core)",
    "org 4.1.3 (core)",
    "packaging 2.4.0 (core)",
    "schema 3.3.4 (core)",
    "settings 2.2.1 (core)",
    "sobject 1.3.6 (core)",
    "source 3.3.3 (core)",
    "telemetry 3.3.4 (core)",
    "templates 56.2.4 (core)",
    "trust 3.6.6 (core)",
    "user 3.5.2 (core)",
    "sfdmu 4.33.15 (user)"
  ]
}
```
### Additional information
<img width="614" alt="image" src="https://github.com/forcedotcom/cli/assets/97173615/827e768c-11b5-452a-8995-f5e9a6722337">

**Comment by mshanemc** [comment]
Hmm...I can't reproduce that.  Can you uninstall it, try it again, and see if the issue persists?

interestingly, `3.0.13` is from ~3 months ago.  You'll want to use a more recent CLI (which will JIT install a more recent plugin-community since it seems to be fixed.

I *also* couldn't reproduce it using 3.0.13.  How consistently was this happening (it's possible for a CI job to not be able to reach our s3 bucket (where the signatures are stored) for networking reasons and therefore not be able to find the signature file (have seen that occasionally on some of our tests that do the same).

**Comment by petter-eikeland** [comment]
Hi @mshanemc, apologies for very late reply.

It seems like the Docker Image I am using has the `2.25.7` SF CLI version. This would explain why it is trying to retrieve an old `community` version, as you mention.

What's interesting with this version is that it seems like it doesn't find the community plugin versions at all. When executing `yes | sf plugins install community`, it fails with: 

```
? This plugin isn't signed by Salesforce. Only install the plugin if you trust
? This plugin isn't signed by Salesforce. Only install the plugin if you trust
2024-04-30T13:40:12.8246056Z its creator. Do you want to continue the installation?, yes
2024-04-30T13:40:12.8246604Z Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
2024-04-30T13:40:12.8246957Z Finished digital signature check.
2024-04-30T13:40:12.8247221Z Installing plugin community@latest... failed
2024-04-30T13:40:12.8247543Z  ›   Error: community does not exist in the registry.
2024-04-30T13:40:12.8247707Z 
2024-04-30T13:40:12.8285227Z ##[error]Bash exited with code '1'.
2024-04-30T13:40:12.8294302Z ##[section]Finishing: Install SF Community
```

So, it's probably just an issue with this specific SF CLI version.

I'll try creating my own Docker Image with a more recent version of the CLI with `community` preinstalled so that I don't have to JIT install it every time.

**Comment by mshanemc** [comment]
@petter-eikeland does it work any better with `sf plugins install @salesforce/plugin-community` ? I tried it both ways, and with that old CLI version, and they were all ok. 

fyi, the behavior of that signature check is
1. connect to our s3 buckets
2. if it finds the expected files (public key and .sig), crypto-validate the signatures
3. if the file is not found, prompt the user

We can't tell the difference between not signed and "couldn't connect" the way s3 buckets work.  

So there's a chance that this is a network/connectivity problem from your container.

---

```
Installing plugin community@latest... failed
2024-04-30T13:40:12.8247543Z  ›   Error: community does not exist in the registry
```
this might be another connection problem.  Otherwise `sf plugins install @salesforce/plugin-community` (the full name) could help

**Comment by petter-eikeland** [comment]
Hi @mshanemc, interestingly, this solved my issue. 

Any thoughts why the built-in JIT plugin install fails?

**Comment by mshanemc** [comment]
Yeah, there was a bug in plugin-plugins that we had found while fixing a bigger one 
https://github.com/oclif/plugin-plugins/pull/776#issuecomment-2012541099

You shouldn't see that behavior (it should work both ways) on more recent CLIs, if you want to confirm the fix.
