### ISSUE TITLE
Provide a CLI command to export an org to source code

### ISSUE THREAD

**Issue by mlamrib** [forcedotcom/cli#287]
**Is your feature request related to a problem? Please describe.**
It's hard to do real continuous integration in SalesForce especially with existing projects without having a package export feature in CLI. 

**What are you trying to do**
Export an org to source code without having to jump through hoops and rely on third party untested plugins/solutions.

**Describe the solution you'd like**
I'd like SF to provide a CLI command "sfdx force:source:export" or something similar that will handle exporting all the org metadata.

**Describe alternatives you've considered**
I've tried the solution documented by Bob Buzzard (http://bobbuzzard.blogspot.com/2018/07/export-metadata-with-salesforce-cli.html) and after wasting a couple of hours researching the "ENOENT spawnsync" error in his node js script, I finally got it to work (by adding a .cmd to the call to sfdx since I'm on windows). But this was quite painful. I've read numerous articles online by dozens of people having the same issue. it would be nice if SF handles this so we can focus on feature development and not jumping through hoops to get work done.

**Comment by keirbowden** [comment]
@mlamrib sorry the solution on my blog didn't work on Windows - I wrote that back in 2018 when I only had access to a Mac so I couldn't test on multiple platforms. If you get into the same kind of situation again, try hitting me up on twitter - I'm usually online and I could have answered this one quickly.

**Comment by mlamrib** [comment]
@keirbowden I'm not sure which blog article you are referring to. Are you referring to Bob Buzzard's article which I linked in my issue?

**Comment by keirbowden** [comment]
@mlamrib yes - Bob Buzzard is my alter ego so I wrote that article.

**Comment by mlamrib** [comment]
Ah. Ok. Thanks! I appreciate you putting out the Node program on github. I ran it and exported the metadata from our SF sandbox. Unfortunately I couldn't do a push because of the 50MB size limit on scratch orgs. Our sandbox is about 450MB in size. Do you know a good workaround? I've read an article that suggested using multiple/different gitignore files and swapping them in and out to push different types of files. But that seems very messy to me. 
Another question if you don't mind. I exported the metadata from another tool and noticed that the file names exported using your program are different than those of that tool. yours had an extension of ".xxx-meta.xml". For example Mobile_Login_Snapshot.snapshot-meta.xml instead of   Mobile_Login_Snapshot.snapshot. Do you know what that's due to?

**Comment by klouf-threshold** [comment]
@mlamrib Scratch orgs are intended for use with package development, versus traditional sandboxes which handle traditional org development. Attempting to push all of the metadata for an org to another org is nearly impossible even for a traditional sandbox, nevermind a scratch org -- I speak from experience on this. If you want to use a scratch org, you should only be pushing metadata that is relevant to the development task at hand rather than all of it.

Some more information on org vs package development (a little more specific as it relates to using Visual Studio Code, but there are trailheads and other documentation that also cover the two different approaches as well): https://developer.salesforce.com/tools/vscode/en/user-guide/development-models/

As far as the file extensions, I'm guessing it's a result of one tool using the Metadata API vs the newer Salesforce DX source format. More info on that here: https://developer.salesforce.com/docs/atlas.en-us.224.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_file_format.htm

One last thing, a shameless plug for a plugin that I wrote for the CLI to be able to build a complete manifest file (like Bob's Node app that you've already discovered): https://www.npmjs.com/package/@zervice/zervice-sfdx-plugins

**Comment by mlamrib** [comment]
@klouf-mp thanks for the info and will definitely check out your plugin. Unfortunately, I'm not a sales force developer. I was tasked with helping our sales force team implement CI/CD. They have been using the org development model so far. I have read and gone through a few trailheads and understand a little bit more about DX development now. 
I have read this article which had some great advice on converting to packages (https://www.salesforceben.com/breaking-your-org-into-packages-salesforce-dx/). But it doesn't seem like an easy/straightforward task. Do you have any pointers/links to other resources on how to break down your DX project so that you can easily do a push of just the feature/relevant task at hand? Also, if you have multiple packages, can you keep them all in the same DX project, or do you need a separate DX project for each package? and how do you handle deployments using CI tools in that case (if you have separate projects especially)?

**Comment by mlamrib** [comment]
@klouf-mp 
ps. I tried installing your plugin and got this error
C:\WINDOWS\system32>sfdx plugins:install @zervice/zervice-sfdx-plugins
Error: unable to verify the first certificate
Do you know how to get around it?

**Comment by klouf-threshold** [comment]
@mlamrib You are correct in that it is often not a simple/straightforward task to transition an existing org to packages. Unfortunately I don't have any more pointers on that, as we have not made that leap yet.

I will note that It is by no means necessary to do package-based development in order to have a CI/CD setup. It is very possible to have a setup in which incremental changes are deployed to a sandbox.

As far as the installation error -- the plugin is not signed, so you should get a warning when installing it, but you should just be able to enter 'y' to continue with the install. I do not have access to a Windows machine at the moment, but I was able to install it without issue on a Mac just now.

One last thing (and this is very much a forward-looking statement) -- I did hear at Dreamforce that Salesforce is working on bringing the source-tracking features/functionality of Scratch Orgs to Sandboxes, which should be a huge help in the world of CI. But like I said before, it is still currently possible in the meantime to have a CI setup that does a lot of the same functionality.

**Comment by mlamrib** [comment]
@klouf-mp that's great news for a Monday! I hope they release the feature very soon.
Can you elaborate on your 2nd paragraph? How do you implement automated deployments using the org model, and how do you select the incremental changes? I believe the change-set feature might be using an api to do a comparison behind the scenes to allow delta deployments and that api might be exposed in the CLI. But I suspect that it would be hard to have the org metadata in SCM in that case. 
Again, I really appreciate your thoughts. I wish that SalesForce put some more effort in documenting different scenarios of  migrating to the package dev model and using CI/CD. A lot of the examples they have given in the trailheads are more like "Hello World" examples and that works great for starters. But it doesn't address needs of large enterprises who have more complicated setups.

**Comment by klouf-threshold** [comment]
@mlamrib Currently we use the **git diff** command to determine which files have been modified in a branch and then pass those file paths as arguments to the **sfdx force:source:deploy** command. For local development with Developer sandboxes, we have a bash script to do the diff and deploy that can be used as needed in combination with our CLI plugin and the VS Code extensions/CLI. For QA and Staging sandboxes we use Bitbucket and have their Pipeline functionality configured with a similar script to do the diff and validate/deploy (Github has similar functionality I believe, but I am not familiar with it)

Just to be clear, I am not advocating that this is a recommended solution/best practice, but it is what works fairly well at the moment for our team. Definitely far from perfect or ideal, but as Salesforce continues to update the CLI and add/improve functionality we are likewise able to improve our processes in kind. (And on that note, huge shoutout to Salesforce for all of their work on and commitment to the CLI, VS Code extensions and other developer tools!).

**Comment by mlamrib** [comment]
@klouf-mp "git diff" is a good trick!

**Comment by shetzel** [comment]
>Export an org to source code without having to jump through hoops and rely on third party untested plugins/solutions.

This is possible in recent CLI versions by generating a metadata manifest from an org, then retrieving all source from that org using the generated manifest.
E.g., 
`sf project generate manifest --from-org test@my.org --name my-package.xml`
`sf project retrieve start --manifest my-package.xml --target-org test@my.org --output-dir retrievedSource`

>Salesforce is working on bringing the source-tracking features/functionality of Scratch Orgs to Sandboxes

Yes, this is now also possible
