### ISSUE TITLE
bulk and use-tooling-api cannot be used in the same operation

### ISSUE THREAD

**Issue by VinceFINET** [forcedotcom/cli#2900]
### Summary
I want to gather the dependencies of a specific field (given its salesforce id) from the `REST` endpoint and the `BULKv2` endpoint using the tooling api in both cases.
The later is documented in the salesforce developer blog, but using the curl command not the sf CLI.
Specifying the flags **bulk** and **use-tooling-api** in the same command causes the following error: 
```
--bulk=true cannot also be provided when using --use-tooling-api
  --use-tooling-api=true cannot also be provided when using --bulk
```

### Steps To Reproduce
```
org="xxx"
id="00N0N00000xxxxx"; 
dapiQuery="SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE RefMetadataComponentId = '${id}' OR MetadataComponentId = '${id}'"
sf data query --target-org nvbsat --query "${dapiQuery}" --result-format csv --use-tooling-api > /tmp/dapi-rest-${id}.csv
sf data query --target-org ${org} --query "${dapiQuery}" --result-format csv --use-tooling-api --bulk > /tmp/dapi-bulkv2-${id}.csv 
```

### Expected result
In my example, the first commands and the second commands should return the same kind of data (in terms of structure).
My goal is to illustrate the differences between the two calls.

But the output of the two commands should have the same structure like:
```
MetadataComponentId,MetadataComponentName,MetadataComponentType,RefMetadataComponentId,RefMetadataComponentName,RefMetadataComponentType
00h0N00000XgMqqQAF,abc,Layout,00N0N00000APzTFUA1,xyz,CustomField
00N0N00000APzTFUA1,xyz,CustomField,00N0N00000APzSwUAL,ijk,CustomField
....
```

### Actual result
the second command output nothing in the &1
the error in &2 are the following:
```
Error (2): The following errors occurred:
  --bulk=true cannot also be provided when using --use-tooling-api
  --use-tooling-api=true cannot also be provided when using --bulk
See more help with --help

```

### System Information
terminal: zsh
```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/Users/xxxxx/.local/share/sf/client/2.42.6-2b3c407",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "dev 2.3.1 (user) published 32 days ago (Thu May 02 2024)",
    "info 3.2.8 (core)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 2.4.4 (core)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)",
    "@salesforce/sfdx-scanner 3.24.0 (user) published 33 days ago (Tue Apr 30 2024) (latest is 3.25.0)"
  ]
}
```

**Comment by cristiand391** [comment]
hey, this was requested but we decided not to support it yet because the `MetadataComponentDependency Tooling API` implements a slightly different endpoint for bulk jobs and never left beta, see:

https://github.com/forcedotcom/cli/discussions/2667#discussioncomment-8865387

https://github.com/salesforcecli/plugin-data/pull/843#issuecomment-2010738997

> ❌ can do a bulk query on tooling objects
At first I thought it worked when querying ApexClass but that's available outside tooling, after reading the docs linked in the GH discussion I see this requires adding support for the tooling endpoint to do bulk queries on jsforce, see:
https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_metadatacomponentdependency_bulk2_usage.htm
IMO we shouldn't implement that yet, mostly because:
only MetadataComponentDependency seems to support tooling bulk queries
it's been in beta for a few years and doesn't seem to be a priority (see group info: https://trailhead.salesforce.com/trailblazer-community/groups/0F93A00000020Vu?tab=discussion&sort=LAST_MODIFIED_DATE_DESC)

**Comment by cristiand391** [comment]
if you need to use the API for scripting you could use my API plugin:
https://github.com/cristiand391/sf-plugin-api

I think with that + `jq` you should be able to create the job and query the results.

**Comment by VinceFINET** [comment]
awesome thank you for this !
