### ISSUE TITLE
User Names with slashes do not appear `sf org list`

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#3139]
### Summary
Some user names generated by Salesforce recently (Partner Learning Camp Demo Orgs, SDO orgs) have forward slashes in them, for example: `jason.clark@example.com2024/11/25_12-7-57.demo`.  Logging in to these orgs via `sf org login web` or `sf org login device` works, but the orgs cannot be seen via `sf org list`.

### Steps To Reproduce

1. Create a user name with forward slashes (`/`) in it.
2. Using SF CLI, connect the org and give it an alias: `sf org login -a error-demo`
3. Upon success, verify that the CLI knows about the org:  `sf org display` should display the org details.
4. Try to view the org in the list:  `sf org list`

### Expected result
The org should appear in the list output, showing the user name and the alias

### Actual result
The org is missing

### Additional information
The json file for the org is getting created in a subdirectory, which is probably the issue; for example, logging in as `jason.clark@example.com2024/11/25_12-7-57.demo` creates the file `.sfdx/jason.clark@example.com2024/11/25_12-7-57.demo.json`, like so:

```
[Folder] .sfdx
 - [Folder] jason.clark@example.com2024/
 - - [Folder] 11/
 - - - [File] 25_12-7-57.demo.json
```

### System Information
Running zsh on Mac OS 14.6.1

`sf version --verbose --json` output:
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.68.6",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/jclark/.nvm/versions/node/v20.17.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.10 (core)",
    "@oclif/plugin-commands 4.1.10 (core)",
    "@oclif/plugin-help 6.2.18 (core)",
    "@oclif/plugin-not-found 3.2.28 (core)",
    "@oclif/plugin-plugins 5.4.17 (core)",
    "@oclif/plugin-search 1.2.16 (core)",
    "@oclif/plugin-update 4.6.13 (core)",
    "@oclif/plugin-version 2.2.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.23 (core)",
    "@oclif/plugin-which 3.2.19 (core)",
    "@salesforce/cli 2.68.6 (core)",
    "apex 3.6.3 (core)",
    "api 1.3.2 (core)",
    "auth 3.6.75 (core)",
    "data 3.11.4 (core)",
    "deploy-retrieve 3.15.13 (core)",
    "info 3.4.21 (core)",
    "lightning-dev 1.9.0 (user) published 55 days ago (Fri Oct 11 2024) (latest is 1.9.4)",
    "limits 3.3.40 (core)",
    "marketplace 1.3.6 (core)",
    "org 5.2.4 (core)",
    "packaging 2.9.3 (core)",
    "schema 3.3.42 (core)",
    "settings 2.4.6 (core)",
    "sobject 1.4.46 (core)",
    "telemetry 3.6.23 (core)",
    "templates 56.3.30 (core)",
    "trust 3.7.43 (core)",
    "user 3.6.3 (core)"
  ]
}
```

**Comment by VivekMChawla** [comment]
@jclark-dot-org - Thank you for reporting this issue, and for providing excellent details about what's happening.

Unfortunately, the CLI was created with the expectation that Salesforce usernames would always follow the standard conventions for email addresses, which do not include slashes.  That's why the odd multi-folder breakdown is happening.

We don't intend to do change this, so the workaround would be to change the username and re-authenticate with the CLI.

I'm going to reach out to the Partner Learning Camp and SDO teams and ask them to use `-` separators instead of `/` in their auto-generated user names.

I'm also working to publish a Known Issue for this and will share it here when it's available.
