### ISSUE TITLE
2nd gen package version with ancestor is failing with "protected" visibility

### ISSUE THREAD

**Issue by ennoucas** [forcedotcom/cli#368]
Hello, I'm having issues when creating a package version with ancestor containing a custom object with visibility set to "Protected" --> `xxx: Cannot modify managed object: entity=CustomEntityDefinition, component=01Ixxx, state=MANAGED_RELEASED`

This custom object was packaged first time as "Protected" (<vibility> tag in object-meta.xml file). When using the release version as ancestor and trying to create a new version, I get this error saying I can't change the visibility from public to protected. 

I tried changing the object name, changing the namespace, creating a new package. It happens every time. 

My setup: 
SFDX: sfdx-cli/7.53.0-839fc82926
ISV org acting as dev hub with namespace registry
Dev org with namespace registered

**Comment by clairebianchi** [comment]
@ennoucas I have reached out to the packing team and let them know you are seeing this issue

**Comment by ennoucas** [comment]
@clairebianchi Hello Claire, any news on this one ? Thank you.

**Comment by jairzh** [comment]
+1 Any update for this issue?

**Comment by preddivari** [comment]
We've determined that the issue you reported exists in code owned by another developer team. That team uses only official Salesforce Customer Support channels to address their issues. Therefore, to ensure your issue is addressed, do this:

- Create a [Salesforce Customer Support case](https://help.salesforce.com/s/articleView?id=000384365&type=1).
- Post in the [Trailblazer Community](https://trailhead.salesforce.com/trailblazer-community/groups/0F93A000000HTp1SAG?tab=discussion&sort=LAST_MODIFIED_DATE_DESC) so others can discuss the topic.
- Update this GitHub issue with your support case number for better tracking.

**Comment by mjaggard** [comment]
For anyone else with this issue there seem to be three options available in increasing order of success:
1. [No solution available from Salesforce](https://issues.salesforce.com/issue/a028c00000gAwiyAAC/second-generation-managed-package-version-creation-throws-an-error-cannot-modify-managed-object-entitycustommetadata) which at time of writing says "There isn't a workaround for this issue yet."
2. Stop using 2nd Gen Packages.
3. Stop using Salesforce. (recommended)
