### ISSUE TITLE
Can't retrieve Named Credentials with force:source:retrieve

### ISSUE THREAD

**Issue by aldoforce** [forcedotcom/cli#384]
### Summary

I created a Named Credential in my Sandbox org and can't retrieve it thru CLI with force:source:retrieve -m NamedCredential

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Create a named credential like
![Screen Shot 2020-04-30 at 2 13 53 PM](https://user-images.githubusercontent.com/1487219/80741456-07734380-8af0-11ea-92fd-14842f6a485e.png)

1. From CLI attempt to retrieve metadata component with `sfdx force:source:retrieve -m NamedCredential`

<img width="593" alt="Screen Shot 2020-04-30 at 2 40 51 PM" src="https://user-images.githubusercontent.com/1487219/80741774-9c763c80-8af0-11ea-8b75-5bb53599466f.png">

### Expected result

A new file representing the NamedCredential metadata component should be created in my local file system

### Actual result

No file created, just a `No result found` message as described in the picture

### Additional information

Same behavior if used from OrgBrowser. However, with org browser at least you can see there's a named credential but you can't retrieve it.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.54.4-8ff9ba9cc5 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

➜  crm-salesforce (devops-2.0) sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 3.0.0
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.10.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.10.0 (core)

sfdx-cli 7.54.4 (core)
sfpowerkit 1.44.2-11 (beta)
texei-sfdx-plugin 1.6.0

**OS and version**:
OSX 10.15.3

**Comment by shetzel** [comment]
I just tried to reproduce this and it worked for API version 48.  Please list the output of `sfdx plugins --core` and update if you're not on the latest.

**Comment by aldoforce** [comment]
> I just tried to reproduce this and it worked for API version 48. Please list the output of `sfdx plugins --core` and update if you're not on the latest.

Just updated the plugins, same result.

Maybe something to do with the type of named credential?

**Comment by shetzel** [comment]
I used your screen capture as the basis for the named credential so hopefully it was similar enough.  I used a scratch org so that could be another difference.  If you use a scratch org, does `sfdx force:source:status` show the remote addition?  If you use `sfdx force:mdapi:retrieve` does that also not retrieve anything or is it specific to `source:retrieve`?

**Comment by aldoforce** [comment]
I'm using sandbox, and probably that's the main difference. I tried with another sandbox and i have the same result.

However, when I'm trying to retrieve with `force:mdapi:retrieve` I receive the named credential correctly so this is specific to `source:retrieve`.

Just in case, this is my sfdx-project.json:

➜  crm-salesforce (devops-2.0) cat sfdx-project.json                                                                            
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://test.salesforce.com",
    "sourceApiVersion": "48.0"
}

**Comment by shetzel** [comment]
Can you set `SFDX_MDAPI_TEMP_DIR=mdapi_tmp` env var, run the `source:retrieve` command again and check the mdapi_tmp directory for what the `package.xml` looks like as well as (if it exists) the contents of the unpackaged dir?  Both of those commands use the metadata API so trying to narrow the problem down to manifest generation, source conversion, or command reporting.

**Comment by aldoforce** [comment]
Same: `No results found`
Exploring `mdapi_tmp` I have the temporary unpackaged dir and within I do have:

`package.xml` and `namedCredentials` folder with the **correct metadata retrieved**.
For some reason this is not moving the folder to the default 'force-app' source folder.

**Comment by shetzel** [comment]
That's good to know.  So the metadata is retrieved, but not copied to the correct location in the project.  That indicates a problem in converting from the mdapi format to the source format (and everything after).

I suspect I'll have a difficult time reproducing this so that's why I'm trying to narrow this down here.  If you could try one more thing it would be interesting to see what happens.  In your project dir there is a `.sfdx/orgs/` dir.  That contains some local source tracking info per org that might be causing a problem.  Locate the username directory for your sandbox and move it somewhere else temporarily.  Then retry the `source:retrieve` command again.  If the command is successful, could you please run that command again appending `--dev-debug` and redirect the output to a file.  Then copy the moved directory back (overwrite the existing one) and run the command appending `--dev-debug` again and redirect output to another file.  Assuming the first command passes and the 2nd one fails, I'd love to inspect the differences between those 2 files to discover how to repro the bug and a fix it.

Thanks in advance!
