### ISSUE TITLE
UnhandledPromiseRejectionWarning: RetrieveFailed: Entity of type 'EntitlementProcess' (New issue)

### ISSUE THREAD

**Issue by leonardopmacedo** [forcedotcom/cli#497]
Starting SFDX: Pull Source from Default Scratch Org and Override Conflicts

17:23:11.819 sfdx force:source:pull --forceoverwrite
(node:15700) UnhandledPromiseRejectionWarning: RetrieveFailed: Entity of type 'EntitlementProcess' named 'my entitlement process' cannot be found
    at MdapiPullApi._processResults (C:\Program Files\Salesforce CLI\client\node_modules\salesforce-alm\dist\lib\source\sourcePullApi.js:178:36)
    at MdapiPullApi._postRetrieve (C:\Program Files\Salesforce CLI\client\node_modules\salesforce-alm\dist\lib\source\sourcePullApi.js:147:21)
    at C:\Program Files\Salesforce CLI\client\node_modules\salesforce-alm\dist\lib\source\sourcePullApi.js:94:29
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15700) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
ERROR running force:source:pull:  Entity of type 'EntitlementProcess' named 'my entitlement process2' cannot be found
17:23:20.419 sfdx force:source:pull --forceoverwrite

PS D:\Git Projects\somattos> sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ salesforce-alm 48.24.3 (core)
sfdx-cli 7.65.6 (core)
PS D:\Git Projects\somattos> 

I don't think it was solved (https://github.com/forcedotcom/cli/issues/480)... I'm facing many issues with EntitlementProcess in a new scratch org.
I created a new Scratch, did the first push and did a pull, I receive many conflicts (I didn't change anything), so I had to do the pull -f and the CLI gave me error of EntitlementProcess not found... It's another open issue, but now, I have 2 issues at same time, one triggering another. =/

**Comment by shetzel** [comment]
@leonardopmacedo - Is your scratch org empty or is it created from an org snapshot?  If it's a new, empty scratch org then there should be nothing to pull immediately after a push.  If your scratch org is based on a snapshot and is already provisioned with metadata, then you'll have to reset the state of source tracking at some point to align the project with the scratch org.  Use the new source tracking commands for that; `force:source:tracking:reset` and `force:source:tracking:clear`.  Be cautious when using those commands since they directly affect source tracking state.  As an example, if you know that source tracking should be clean (i.e., nothing new/changed/deleted local or remote after initial push) then you can run `force:source:tracking:reset` after the push and source tracking state should be clean, meaning `force:source:status` will report "No results found".

**Comment by leonardopmacedo** [comment]
@ shetzel tks for reply, I'm already doing this, but I would like to know why the CLI has this behavior.
