### ISSUE TITLE
Killing sfdx does not cancel the running job

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#549]
**What are you trying to do**
When sfdx is killed with a signal, like just ctrl-c'ing it, the job isn't cancelled and keeps running

**Describe the solution you'd like**
When I kill sfdx that's doing a test run or deploy, I'd expect the job to be cancelled. I expect this behavior because **sfdx keeps running until the job is complete.** If sfdx instantly stopped running and returned a jobid, I'd expect to have to poll for that job id myself and juggle the id to cancel the build. But because sfdx keeps running, it gives the impression it's running along with the test run, so cancelling it should intuitively cancel the build.

Either this could be default behavior (preferred) or flagged:

> sfdx force:source:deploy -u Env --checkonly **--cancel-on-exit**

**Additional context**
This is another example of sfdx being an inconsistent tool in a modern development toolchain. It doesn't play nicely with status codes, nor does it play nicely with cancelling.

**Comment by amphro** [comment]
I don't agree that it should cancel the job. Waiting for a job to finish is much different than it **is** the job which is what that implies. FWIW you can return the job ID immediately with `--wait=0` but it is not the default so your point is still valid.

Either way, this is a very opinioned behavior and I would be curious to know more of the community's opinions on the matter.

If we didn't do it by default but it was still behaviour we supported, I like a config option better since realistically if you want that behavior you want it for all commands.

```
sfdx force:config:set cancelJobsOnExit=true --global
# Both commands bellow would cancel the job if ctrl+c out of it.
sfdx force:source:deploy -u Env --checkonly
sfdx force:apex:test:run
```

**Comment by swampthing1984** [comment]
will try to eat the star :-0*
