### ISSUE TITLE
sfdx force:mdapi:listmetadata -m Layout returns undefined

### ISSUE THREAD

**Issue by benahm** [forcedotcom/cli#55]
### Summary

Unable to list metadata for "Layout" metadata type using Salesforce CLI

### Steps To Reproduce:

Auth to any org and run

    sfdx force:mdapi:listmetadata -m Layout

### Expected result

List of layout available in the org (the default authenticated org)

### Actual result

Value : "undefined"

### Additional information

See screenshot below

**SFDX CLI Version** V45.0

**OS and version**: Windows 10

![image](https://user-images.githubusercontent.com/3356566/55114362-05b3a100-50e2-11e9-9985-319d9f2a36c2.png)

**Comment by clairebianchi** [comment]
@kfidelak94 can you take a look at this issue

**Comment by benahm** [comment]
Hi, this is still not solved, even with the latest version of the Salesforce CLI

**Comment by kfidelak94** [comment]
@benahm We are tracking this issue internally through our Metadata API team rather than the CLI team.  The internal work item, for reference, is W-5982601.  We are hoping to address this in an upcoming sprint.  I'll work to get a Known Issue created so it can be tracked externally through that as well.

**Comment by kfidelak94** [comment]
@benahm  Here is the Known Issue for your reference, and to track progress from.  https://success.salesforce.com/issues_view?id=a1p3A000001SGUYQA4
