### ISSUE TITLE
Ability to disable "Updating source tracking" for CI/CD

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#558]
**Is your feature request related to a problem? Please describe.**
We use CI/CD for testing pull requests and it'd be nice to be able to turn off the source tracking update functionality because it adds an unnecessary additional 5-10 minutes to our job since we aren't pushing and pulling changes for these scratch orgs. Since we're paying for compute time for our CI/CD, these 5-10 minutes add up over time.

**Describe the solution you'd like**
A switch for the `force:source:push` that skips the source tracking update step

**Comment by daveespo** [comment]
How did you measure that source tracking adds 5-10 minutes to a push to a scratch org?

**Comment by ghost** [comment]
This will vary depending on the size of your deployment, but in our case, Circle CI took 17m 42s to complete the `sfdx force:source:push` step. On the Salesforce Deployment Status page, the deployment only took 10m.

The Circle CI streaming log was stuck on the following message for a while before it outputs the list of components that are added.
>Updating source tracking for 9744 pushed components...

**Comment by ghost** [comment]
It looks like the `force:source:push` command is internally converting the source to the MDAPI format, doing a MDAPI deploy and then syncing the source tracking. I may be able to forego the push command and do the other two commands instead. 🤔

**Comment by vc4u** [comment]
Mine took 52 minutes (approx). And there weren't that many components in my repository as well.

```
Job ID | 0Af5600000sYCjrCAG
SOURCE PROGRESS | ████████████████████████████████████████ | 2302/2302 Components
Updating source tracking for 2302 pushed components...
```

It took only 4-5 minutes to push all source into the scratch org though.

---- UPDATE:
I tried creating more scratch orgs, they took considerably less time than the first attempt. Not sure if it matters, but my first attempt today at generating new scratch org was after at least 14 days. After it took 50+ minutes first time, the next scratch org was generated with all code pushed in around 20 minutes.

**Comment by maaaaarco** [comment]
same here actually. We have a repository with slightly more than 5k components. We are also experiencing slower Push and Pull performances.... wonder if it's also related to that

**Comment by shetzel** [comment]
The next release scheduled for this Thursday will have a new environment variable called, `SFDX_DISABLE_SOURCE_MEMBER_POLLING` to disable the polling of SourceMembers.  Set this env var to `true` to forego updating source tracking.  Keep in mind that when using this env var, source tracking will be unreliable.  However, you can manage it yourself by using the `force:source:tracking:reset` command if you need to.  Look for the release notes this week for more information.

@travisagentsync - after updating to this week's patch release, if this addresses your issue please close.  Also, you are correct that the source commands convert between source format and mdapi format behind the scenes.  Another alternative would be to use the source convert command followed by the mdapi deploy command to ignore source tracking.  Alternative 2 would be to use the source deploy command since (currently) it does not use source tracking.

**Comment by imTachu** [comment]
I wonder if this is actually working for anyone, I did a tiny test creating a scratch org without setting a value for  `SFDX_DISABLE_SOURCE_MEMBER_POLLING`, it took 20 mins 1 sec, after setting `SFDX_DISABLE_SOURCE_MEMBER_POLLING` to `true`, it took 19 mins 59 secs. Am I maybe missing something?
