### ISSUE TITLE
Source:push --jobid/ source:report to reconnect similar to deploy:report

### ISSUE THREAD

**Issue by Erisiel** [forcedotcom/cli#62]
**Is your feature request related to a problem? Please describe.**
Yes. Initial source push command to a new scratch org takes a long while to complete (20-40 minutes average), however sometimes the command gets interrupted or disconnects or otherwise loses track of progress.

Background: We have an application build on the salesforce platform in the course of several years and is extensive in size.  By now we have options on the salesforce platform and coding guidelines that will allow us to separate parts in to loose artifacts eventually but we are not there yet. 

**What are you trying to do**
We have created a build script with several steps which takes a while to complete. Part of this script is performing a long duration source push. I would like this push command to have a more stable experience by being able to continue / poll for completion so that the script can runs without being dependent of source push finishing in 1 go without hiccups. 

**Describe the solution you'd like**
Similar to the mdapi deploy/retrieve commands, it would be useful to be able to retrieve the progress of / reconnect to the last push performed to have the CLI sync more quickly then having to perform the push again. 

**Describe alternatives you've considered**
Another solution at least for the connection failure could be that the cli command reconnects by itself. 

**Additional context**
Seen cases:  
1. Connection lost. Command fails and needs to run again
2. Command runs indefinitely even though implementation status says it has completed

**Comment by keirbowden** [comment]
We're seeing occasional problems where the force:source:push command doesn't return, although we can see from the deployment status in the org that it has completed some time ago. In order to proceed we have to kill the command, but it appears that it is stuck prior to making the tracking changes, as the next time we run force:source:push it does the whole codebase again. Having a way to be able to pull the status of the deployment from the org and update the local tracking information would save us quite a lot of time.  It would also be nice to be able to report the progress of the deployment, rather than the developer having to wait until the end.

Failing that, some mechanism where we can tell the CLI that the local filesystem is in sync with the org, so update the tracking information to reflect that would be really useful.

**Comment by keirbowden** [comment]
Looks like the new force:source:tracking:reset command gives me the ability to tell the CLI that everything is in sync - nice.

**Comment by mshanemc** [comment]
the replacement command for `push` (`project deploy start`) has a sibling command (`project deploy resume`) that will let you "finish" a deploy that times out or is otherwise interrupted.  It also offers a `--use-most-recent` option which will used the most recent deployId from your local machine.

In this case, finishing also includes getting all the post-deploy source tracking sorted.

https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71950-april-6-2023-stable-rc
