### ISSUE TITLE
Support for TestSuites in force:source:deploy and force:mdapi:deploy

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/cli#621]
**Is your feature request related to a problem? Please describe.**
There is no possibility to run test suites using either sfdx force:source:deploy or sfdx force:mdapi:deploy commands. When using RunSpecifiedTests and -r flag to specify the name of the test suit, it just does not run any tests. 

**What are you trying to do**
Run test suite while deploying to org.

**Describe the solution you'd like**
A dedicated flag for test suits or support in --runtests flag for test suites. 

**Describe alternatives you've considered**
I could mention all of the classes I want to run, but then we often encounter a limit with command size.

**Comment by shetzel** [comment]
Hi @yahirah - this is a limitation of the metadata API.  https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm
Since the CLI uses the metadata API for deploys it is limited to what that API provides.  Others have asked for the same thing so perhaps you could use the [IdeaExchange](https://ideas.salesforce.com/s/about) to vote for your feature request to get it supported within the metadata API.
