### ISSUE TITLE
Cannot deploy Custom Fields by package.xml or by Command Line.

### ISSUE THREAD

**Issue by rahulkapoor83** [forcedotcom/cli#625]
### Summary

While Deploying Custom Fields using Command or by package.xml - it shows 
=== Deployed Source
No results found

### Steps To Reproduce:

1. Retrierved a field by below command and it is successful:

![image](https://user-images.githubusercontent.com/71480553/93735189-baf0e780-fbf9-11ea-9f0e-3cef4fd10bff.png)

2. Deploying same field shows = "No results found.

![image](https://user-images.githubusercontent.com/71480553/93719888-278cc780-fba3-11ea-8c55-d1ec983a3cbf.png)

3. Try to do same operation using package.xml. First try to retrieve using package.xml

![image](https://user-images.githubusercontent.com/71480553/93718043-1a69db80-fb97-11ea-886c-da72ff55c902.png)

![image](https://user-images.githubusercontent.com/71480553/93719908-45f2c300-fba3-11ea-8b55-b233fe297b94.png)

That Works !!

4. Now lets try to deploy same field using same package.xml

![image](https://user-images.githubusercontent.com/71480553/93719921-5c008380-fba3-11ea-8f21-888f879d32d5.png)

**Its not working.** 

### Expected result

Custom Fields should get deployed by package.xml or by SFDX command.

### Actual result

Custom Fields are not getting deployed by package.xml or by SFDX command.

### Additional information

Version: 1.49.1 (user setup)
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/71480553/93720282-a682ff80-fba5-11ea-959e-5991acaa975f.png)

**Comment by renanlq** [comment]
Same from here, but problems with manifest is elder than the last update, see here: https://github.com/forcedotcom/cli/issues/156

**Comment by rahulkapoor83** [comment]
@shetzel - Can you please provide the ETA of the next patch where this issue will be addressed.

Thanks,
Rahul

**Comment by shetzel** [comment]
ETA of next patch is Thursday, Oct 1st.

**Comment by rahulkapoor83** [comment]
@shetzel - I still don't see this fix available with latest update,

**Comment by shetzel** [comment]
Looks like the fix didn't make it into the last release as expected.  We're doing an e-release today that includes the fix so look for it soon.  Sorry for the delay.

**Comment by akashpunera** [comment]
@shetzel is this resolved? i am still facing this issue with version 7.75.0

**Comment by shetzel** [comment]
The fix is in CLI version 7.76.1

**Comment by jitendrabhagatdevops** [comment]
Hi @shetzel - As you mentioned in the latest reply ---> The fix is in CLI version 7.76.1

Still it is not working, in the version 7.76.1


+ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.1.1 (core)
������ templates 50.1.0 (core)
������ salesforce-alm 50.1.1 (core)
������ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
������ apex 0.1.1 (core)
������ custom-metadata 1.0.10 (core)
sfdx-cli 7.76.1 (core)
