### ISSUE TITLE
Error while reteiving source from manifest from Package.xml - ERROR running force:source:retrieve: core_1.SfdxProject.resolveProjectPathSync is not a function

### ISSUE THREAD

**Issue by keyuripatel01** [forcedotcom/cli#629]
### Summary
Trying to use "Retrieve source in Manifest from Org" from package.xml but getting error:-  ERROR running force:source:retrieve:  core_1.SfdxProject.resolveProjectPathSync is not a function
i want to update my template with the changes made in the Master application

### Steps To Reproduce:

1) Created project in with "Sfdx : Create project with Manifest" - Analytics
2) connected the ORG By "Sfdx : Auth ORG"
3) Trying to Retrive the source / Einstein app details by using command - "Retrieve source in Manifest from Org" from package.xml 

### Expected result
Should retrieve the Einstein analytics app assets / apps from Source org

### Actual result

cannot retrieve due to this error - ERROR running force:source:retrieve:  core_1.SfdxProject.resolveProjectPathSync is not a function

### Additional information

following this document ERROR running force:source:retrieve: core_1.SfdxProject.resolveProjectPathSync is not a function
already installed CLI Plug in https://developer.salesforce.com/tools/sfdxcli

**Comment by shetzel** [comment]
It's important to fill out the entire issue template otherwise we just have to ask you for it anyway.  What is the output of `sfdx plugins --core`?  If you have a version of the `salesforcedx` plugin that does not state `(core)` then you can try uninstalling it to get back to the core version and try your command again.  To uninstall, run `sfdx plugins:uninstall salesforcedx`.

**Comment by brunotissi** [comment]
Hi, i'm facing the same issue.

Summary
Trying to use "Retrieve source in Manifest from Org" from package.xml but getting error:- ERROR running force:source:retrieve: core_1.SfdxProject.resolveProjectPathSync is not a function
I want to insert data into my org from a XML file

Steps To Reproduce:
Created project in with "Sfdx : Create project with Manifest" - sandboxTest
connected the ORG By "Sfdx : Auth ORG"
Trying to Retrive the source by using command - "Retrieve source in Manifest from Org" from package.xml

Expected result
Should retrieve data from Source org

Actual result
cannot retrieve due to this error - ERROR running force:source:retrieve: core_1.SfdxProject.resolveProjectPathSync is not a function

Additional information
following this document ERROR running force:source:retrieve: core_1.SfdxProject.resolveProjectPathSync is not a function
already installed CLI Plug in https://developer.salesforce.com/tools/sfdxcli

sfdx plugins --core on my machine:

C:\Users\Bruno Tissi Sysmap>sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 49.11.0 (core)
└─ apex 0.0.9 (core)
sfdx-cli 7.74.1 (core)

**Comment by shetzel** [comment]
Does the same thing happen if you run the retrieve command from powershell?
E.g., `sfdx force:source:retrieve -x package.xml`

This error happens when the `salesforce-alm` plugin uses an older version of `@salesforce/core` that doesn't have recent changes made, such as the `SfdxProject.resolveProjectPathSync` function.  Completely uninstalling and doing a fresh install should theoretically fix it, but those are drastic steps and we need to find the root cause of this.

**Comment by brunotissi** [comment]
I had two users on my machine with different salesforce CLI versions installed. I completely uninstalled the cli for both users, did a fresh install in one of those users and then it worked as it should.
