### ISSUE TITLE
Can't Push Source after just Adding/Changing the Description to a Custom Object

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#630]
### Summary

Can't Push with `sfdx force:source:push --json --loglevel fatal --forceoverwrite` after just Adding/Changing the Description of a Custom Object.

### Steps To Reproduce:

- Create a Custom Object in the UI without Description and add a Mater Detail field related to Asset (Standard Object).
- Create a sfdx project and add this Custom Object to it. Make sure the Metadata contains the attribute `<externalSharingModel>ControlledByParent</externalSharingModel>`. Also, ensure the `<description></description>` attribute is not present.
- Create a Scratch Org(SO) and deploy this package with `sfdx force:source:push --json --loglevel fatal --forceoverwrite`. Ensure it deployed without any errors.
- Open the Custom Object metadata and just add `<description>Object Description</description>`
- Try to push the source again to the same SO and you will see the following error message, which does not relate to just adding/changing the description:

![image](https://user-images.githubusercontent.com/55927613/93899461-3f239780-fcec-11ea-92a6-d576ebfc19a3.png)

If I remove the `<externalSharingModel>ControlledByParent</externalSharingModel>`from the metadata it can't be deployed again, and the same error is thrown.

### Expected result

Since I just added the description to the xml/metadata file, the object should deploy without any error messages.

### Actual result

SFDX throws an error message that is not related to adding/changing the description in the object metadata file.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
![image](https://user-images.githubusercontent.com/55927613/93899738-87db5080-fcec-11ea-8a70-c36c6a8da16e.png)

**OS and version**: Windows 10

**Comment by mdonnalley** [comment]
@AllanOricil in order to successfully push the object, you need to also make a change to the field as described here: https://help.salesforce.com/articleView?id=000334872&type=1&mode=1

I admit that this isn't ideal behavior but we're constrained by the API here. We _could_ do some things in the CLI to work around this use case but that would amount to a feature request. For now I'm going to close this since it's working as documented. But feel free to open a new issue and mark it as a feature request
