### ISSUE TITLE
Missing stack trace when test fails since 14/01 release

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#807]
### Summary

CLI human output format has changed after 14 January release. It is definitely step in good direction as it is more readable but is missing stack trace or a least line where error occurred (most top entry from stack trace).

### Steps To Reproduce:

Run test class that fails with some error.

### Expected result

I can see in CLI output at which line it failed.
Example Class.testUpdateAccountID.UpdateAccountID: line 48, column 1

### Actual result

![image](https://user-images.githubusercontent.com/5740564/104730267-02b3f580-573a-11eb-9571-54ea38ed7d9f.png)

It show error message but I don't know where it failed.

### Additional information

**SFDX CLI Version** sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3
**OS and version**:Windows 10

**Comment by jamessimone** [comment]
Also suffering from this change. In addition to the stacktrace not appearing - not even the line where the failure occurred, just the message! - this issue is exacerbated by an enormous change in the behavior of the VS Code extension: previously, when tests failed, the Output panel would pop up automatically with the contents of the failure message; there was also a pop-up information status that would tell you that the tests had failed. Now, the only thing that happens when the tests finish running is a message in the status bar: "Run Apex Tests successfully ran." It's possible that the lack of feedback in VS code is directly related to the issue with the stacktrace, which is why I mention it here. The combination of both of these issues has made testing a frustrating experience over the past few days.

**Comment by AndrewRayCode** [comment]
The previous working version of sfdx also used to show the test command being run so that you could copy it into a terminal and tweak the command line flags. That is no longer being shown either.

See also https://github.com/forcedotcom/cli/issues/718. I'm not sure if you can turn off auto updating for the vscode plugin's version of sfdx?

**Comment by PawelWozniak** [comment]
Closing as this is not valid anymore.
