### ISSUE TITLE
Cant install plugins from Private Github Url

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#821]
<b>Description:</b>

I can install my plugin from a private npm without a problem in any machine. But I can't install from using a github url. 

![image](https://user-images.githubusercontent.com/55927613/83697097-00ab8500-a5f6-11ea-9779-6f927504fefe.png)

<b>Expected Behavior:</b> 
Plugin should be installed without a problem as it does when using a private npm repository.

<b>Actual Behavior:</b>
Plugin can't be installed because it can't find a tar file.

System Config and SFDX Version:

![image](https://user-images.githubusercontent.com/55927613/83697241-6730a300-a5f6-11ea-8c06-923c49097ae3.png)

**Comment by amphro** [comment]
We are looking into installing plugins from private repos.

**Comment by AllanOricil** [comment]
@amphro I think this one is related https://github.com/forcedotcom/cli/issues/410
I kind of hacked the lib and I made it work.

**Comment by WillieRuemmele** [comment]
Hi @AllanOricil could you try appending `.git` to your url. This also assumes that you're already authenticated locally with HTTPS. If you're using SSH locally instead of HTTPS, then make sure that your url is structured like `ssh://git@<Your repo>.git` For example, if you tried to do `yarn add` with the url you're trying it will also fail.

**Comment by AllanOricil** [comment]
@WillieRuemmele I don't remember if this was the problem, because I was able to install it given the same https url, but using a public repo from my github account. I will test again anyway, and then I come back with the results. Thank you
