### ISSUE TITLE
Add "-r, --noprompt" flag to sfdx plugins:install command

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#83]
**Is your feature request related to a problem? Please describe.**
If I setup a Jenkins CI build and specify the "sfdx" as a custom tool, I would also want to install custom plugins that I have created to aid in the build process.  Currently, there is no way to execute `sfdx plugins:install foo-bar` without confirming the plugin installation since it is not digitally signed.  Because of this, I cannot use the Jenkins Custom Tool plugin when I need specific custom SFDX CLI plugins as well.

**What are you trying to do**
 I need a way to dynamically setup the SFDX CLI and plugins that I want to install via the Jenkins custom tool option.  

**Describe the solution you'd like**
I would like a "-r, --noprompt" flag be added to `plugins:install` command so that I can automate on my CI builds the installation of the plugin after the installation of the SFDX CLI itself.

**Describe alternatives you've considered**
I could manually install the SFDX CLI and the plugins on the Jenkins server and not utilize the "custom tool" option, but then I would not be able to dynamically spin up slave Jenkins instances as needed.

**Comment by genoud** [comment]
Hello @ImJohnMDaniel 
A workarround to this issue:
`echo y | sfdx plugins:install sfpowerkit`

**Comment by ImJohnMDaniel** [comment]
@genoud -- Thanks for the tip.  That is exactly what we ended up doing and what led to this feature request.  ;-)

**Comment by jpmonette** [comment]
@genoud That saved my life - thanks!

**Comment by mshanemc** [comment]
@ImJohnMDaniel there's two other more elegant options I'd suggest.

1. if you're doing other npm installs for your CI, add your plugins as a dependency and then plugins:link them from the node_modules folder (when using `plugins:link` you don't get the code-signing check).
2. add those plugins to your `unsignedPluginAllowList.json`.  More info about that file here here: https://developer.salesforce.com/blogs/2017/10/salesforce-dx-cli-plugin-update.html 

1 is probably the better option for CI because your CI may get some npm-caching benefits and more granular control of which version of the plugin you're running.

**Comment by aheber** [comment]
@mshanemc, I'm on windows and this may be a more windows-specific problem but I've found that when I have a plugin linked then execution of all commands is slower as it seems to re-compile/process the linked plugins every time. I have never dug into the root cause, I just don't leave plugins linked as much as I used to.

(edited as I realized that solution was already provided above)

**Comment by ImJohnMDaniel** [comment]
@mshanemc -- Apologies, I did not see your earlier comment from Dec 4, 2020.  I am aware of both options that you are referring to in that post and neither are an option for me.

Just curious, why are you designating this as "wontfix".  I would expect this to be an extremely small LOE -- Simply add the flag and put in an if/then statement.

**Comment by mshanemc** [comment]
It's the type of thing that won't fly with security.
