### ISSUE TITLE
Give swags/prizes/titles or some sort of compensation for everyone that is constantly helping Salesforce for free here in Github

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#846]
**Is your feature request related to a problem? Please describe.**
No, is just that I and other developers are helping a billionaire company to provide better services to all their customers for free and I thought that it would be cool if SF could give some kind of compensation to us, or if we can get a contract to keep doing so. I'm doing the work of a PO and a QA here quite often, and I'm sure I'm doing a good job and delivering value to SF and I would like to receive compensation for it. If it was a small business or an open-source project of a single developer I would not ask for anything, but it is Salesforce.

@mshanemc @amphro @clairebianchi

**Comment by ntotten** [comment]
While I understand the reasoning to some degree, this isn't something we will be doing - at least not as a policy. First, it's just not practical as we have no means of tracking, deciding level of contribution (i.e. do you get a t-shirt or sweatshirt), and distributing this sort of thing There are all kinds of issues like taxes that would need to be dealt with that we aren't going to get into because it would take away time from actually building the product. Second, contribution isn't mandatory. We run our projects as open source for the benefit of our community. People use the source to learn about the product, to solve problems, to request new features, to report issues, etc. While it is true that some people contribute bug fixes or features - and we very much appreciate that - I don't believe the people doing so are doing it for compensation. We might occasionally send a thank you for outstanding contributions, but it's not something we will do as a policy.

If you would like to get paid to contribute, [we are hiring](https://www.salesforce.com/company/careers/). :) Regardless, we love working with the community to make the Salesforce Developer experience even better.

Edit 1: It was pointed out on Twitter that maybe I shouldn't imply we will "never" do this. IF there was some sort of of program for managing this that didn't take away time from building the actual product that would certainly change things. But as it stands right now, this doesn't exist and I really don't think it's something we would prioritize above building features/fixing bugs.

**Comment by ChuckJonas** [comment]
I think most of us contribute because:

A: we want to improve our own/teams DX & productivity
B: it makes you a better developer to debug & develop on large codebases outside of what you work in on a daily basis.

They also sometimes put major contributions in the change log, which is honestly very nice, but not something they have to do.

The Salesforce community is already way too focused on internet points, certifications, hoodies and plush children's toys (harsh I know 😜 ).

PS: I will say that for one of my earlier contributions ([Adding diagnostics for deploy errors](https://github.com/forcedotcom/salesforcedx-vscode/pull/717)), the code was rebased in a way in which I didn't get credited for the lines on github, and thus don't even show up as a contributor.  Not a huge deal, but something that should be avoided if possible.

**Comment by ntotten** [comment]
> PS: I will say that for one of my earlier contributions (Adding diagnostics for deploy errors), the code was rebased in a way in which I didn't get credited for the lines on github, and thus don't even show up as a contributor. Not a huge deal, but something that should be avoided if possible.

This is a valid point. My understanding is the reason we do this is because external contributors can't run all the tests. I'll mention this to the team though.
