### ISSUE TITLE
Email templates doesn't retrieve .email file in VSCode

### ISSUE THREAD

**Issue by KavyaRaoNeelagiri** [forcedotcom/cli#853]
When i add email template in Package.xml (tried with version 46,47,48,49 and 50)
<types>
        <members>unfiled$public</members>
		<members>unfiled$public/Service_Credits_Approval_Email</members>
		<name>EmailTemplate</name>
</types>
and then do "Retrieve it from source org", it doesnot retrieve text in that email template.
The files retrieved are "Service_Credits_Approval_Email" EMPTY FOLDER (not file) and "Service_Credits_Approval_Email.emailFolder-meta.xml" file which has something like below. I cannot see text of that file anywhere and when i deploy it, t deploys email template with no text in it
<?xml version="1.0" encoding="UTF-8"?>
<EmailTemplate xmlns="http://soap.sforce.com/2006/04/metadata">
    <available>true</available>
    <encodingKey>ISO-8859-1</encodingKey>
    <name>Service Credits Approval Email</name>
    <style>none</style>
    <subject>Service Credit Approval Request</subject>
    <type>text</type>
    <uiType>Aloha</uiType>
</EmailTemplate>

**Comment by mdonnalley** [comment]
@KavyaRaoNeelagiri Can you update the description to adhere to our bug template:



### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:
