### ISSUE TITLE
Node.js used by  sfdx-cli/8.89.2 does not support Windows 7 by default

### ISSUE THREAD

**Issue by OnlyCookie** [forcedotcom/cli#898]
**Summary**
The recent update which was automatically pushed includes updating Node.js to v14.15.4. Since this version of Node.js does not support Windows 7, it made SFDX unusable for Windows 7 users without some hack.

When running SFDX, Windows 7 users will get the error:
`Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.12:30:07.195`

We weren't notified that Salesforce CLI will no longer support Windows 7. The [documentation from salesforce](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm) mentions "Windows—Windows 7 (64-bit and 32-bit) or later" as the System requirements, so we do expect it to still work without us having to modify the sfdx.cmd file.

**Steps To Reproduce:**

1. Using a windows 7 machine, install the latest version of Salesforce CLI
2. Run sfdx -v

**Expected result**
Command is executed, and the version is returned.

**Actual result**
Error message given:
`Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.12:30:07.195`

**Additional information**
**SFDX CLI Version(to find the version of the CLI engine run sfdx --version):** 
sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

**SFDX plugin Version(to find the version of the CLI plugin run sfdx plugins --core):**
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
auth 1.4.8 (core)
config 1.2.4 (core)
etcopydata 0.5.7
generator 1.1.5 (core)
salesforcedx 51.1.1 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 51.3.0 (core)
├─ apex 0.1.4 (core)
├─ user 1.1.2 (core)
├─ salesforce-alm 51.1.1 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdmu 3.9.4
sfdx-cli 7.89.2 (core)
telemetry 1.1.1 (core)

**OS and version:** 
Windows 7

**Comment by amphro** [comment]
We apologize for not updating the documentation and will do so now. Windows 7 is [no longer supported by Microsoft](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962). Node will [not support a version of Windows that Microsoft doesn't support](https://github.com/nodejs/node/pull/31954), which makes it improbable for us to support it since we are built on nodejs. It doesn't mean that node14 won't work on windows 7, it just isn't supported.

You have several options:

1. Install the [Salesforce CLI using NPM](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm) on a node version that doesn't have that check.
2. Set the environment variable (NODE_SKIP_PLATFORM_CHECK) as highlighted above. 
2. [Turn off auto-updates](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm#sfdx_setup_install_plugin_version) _(set `SFDX_AUTOUPDATE_DISABLE=true` globally)_ and [install an old version](https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v7.81.0-7b953c80d1-x86.exe).

_Again, these are not **supported** options but should unblock you so you can still use the CLI._
