### ISSUE TITLE
Cannot retrieve reports and Dashboards via sfdx force:source:retrieve

### ISSUE THREAD

**Issue by reda-benhemmouche** [forcedotcom/cli#90]
### Summary

Trying to retrieve  Reports and dashboards from a Dev Sandbox (i.e., non Scratch org) with the command

```
sfdx force:source:retrieve -m Report
sfdx force:source:retrieve -m Dashboard
```

gives no results returned, when there are a lot of reports and dashboards in the Sandbox. 

### Steps To Reproduce:

1.  Connect a non-Scratch org which contains reports
1.  Run `sfdx force:source:retrieve -m Report`
1. Run `sfdx force:source:retrieve -m Dashboard`

### Expected result

get report and dashboards

### Actual result

```
=== Retrieved Source
No results found
```

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**: sfdx-cli/7.6.0-28071a499b darwin-x64 node-v10.15.3

**SFDX plugin Version**: no plugins installed

**OS and version**: MAC OS High Sierra 10.13.6 (17G5019)

**Comment by enreeco** [comment]
I have the same problem in a sandbox org. I succesfully can run:
`sfdx force:source:retrieve -m Type:Name`
but no luck with
`sfdx force:source:retrieve -m Type`
or:
`sfdx force:source:retrieve -x path/package.xml`
Sandbox API level is 45.0

I also tried with a summer 19 org and still some types are not retrieved at all

**Comment by enreeco** [comment]
I also tried with a summer 19 org and still some types are not retrieved at all

**Comment by clairebianchi** [comment]
@reda-benhemmouche can you check to see if your reports and dashboards are visible to others. when you create reports and dashboards they are automatically set to private and can't be retrieved.

**Comment by AndrewRayCode** [comment]
I'm not sure if the above is correct, I don't see any options to make a dashboard itself "public" when editing it. I was able to do this, it was mildly nightmarish to figure out so documenting the steps:

List all dashboards with SOQL: `SELECT Id, DeveloperName, FolderName FROM Dashboard`

Guess which one is yours, since the DeveloperName is something like "23jf0923jf0293jf"

Take the folder name and remove spaces (not sure if this is the same for everyone) and retrieve this:

```
sfdx force:source:retrieve -m 'Dashboard:FolderName/029fj2039jf023j23' -u TargetInstance
```

Or add it to your package.xml and pull that down:
```
    <types>
        <members>FolderName</members>
        <members>FolderName/029fj2039jf023j23</members>
        <name>Dashboard</name>
    </types>
```

It then should pull down the file. Following these steps, I was able to pull down a dashboard without changing any visibility settings.

Nothing else worked, not `sfdx force:source:retrieve -m 'Dashboard:*'` or `sfdx force:source:retrieve -m 'Dashboard'` etc

**Comment by pushyka** [comment]
just to add in case others see AndrewRayCode answer, to avoid the guessing part, add `Title` to your query which will be the friendly dashboard name. It is the equivalent of the `Name` field on the report table. And use `Folder.DeveloperName` which will give you api name of the dashboards folder (there is no equivalent on the report table that I can see)

`SELECT Id, DeveloperName, Folder.DeveloperName, Title FROM Dashboard`
`SELECT Id, DeveloperName, FolderName, Name FROM Report`

And once you have successfully pulled it down, I'd recommend renaming the dashboard metadata filename and the reference in the package xml from the sf-generated one to something that makes a bit more sense before committing to repo if that is what you are doing.
