### ISSUE TITLE
Bulk upsert to TopicAssignment table does not work

### ISSUE THREAD

**Issue by rickschmidt** [forcedotcom/cli#93]
### Summary

force:data:bulk:upsert does not work for the TopicAssignment table. I've tested using workbench and other anon apex and can confirm my source data is good and permissions enabled.

### Steps To Reproduce:

1.  `sfdx force:data:bulk:upsert -s TopicAssignment -i Id -f ~/path/to/csv`

CSV Header:
TopicId, EntityId
0TO...,001...

### Expected result

The data load should complete with the bulk api like other tools.

### Actual result

ERROR running force:data:bulk:upsert:  No create/update access for object:TopicAssignment

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.6.0-28071a499b darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 45.13.0 (core)
**OS and version**:
macOS 10.14.5

**Comment by mshanemc** [comment]
@rickschmidt we've got an updated version of the `force:data` commands coming out.  Would you be willing to re-test this bug using that?  And if it still doesn't work, let me know?

Here's the instructions for previewing that new version.
https://github.com/forcedotcom/cli/issues/907

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9036354](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008m4fYAA/view)

**Comment by rschmidtSFDC** [comment]
No it does not work after updating to the preview. I verified my CSV with another tool. 

After looking at this with 2021 eyes I don't think it will ever work as long as you can not discriminate between an insert and an update operation(unless I'm missing something in the preview or existing functionality). Since Externalid is required an upsert is implied.  TopicAsssignment only permits inserts as verified through describe calls.
