### ISSUE TITLE
Job Id is a required field when trying to cancel a deploy

### ISSUE THREAD

**Issue by trentchilders** [forcedotcom/cli#982]
### Summary
According to documentation, job id is an optional field when running `sfdx force:mdapi:deploy:cancel`
https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_mdapi.htm

However, when I try to run this command, specifying the org with the -u parameter.

I get the following error:
```
ERROR running force:mdapi:deploy:cancel:  A required parameter [jobid] is missing.
```

This seems to go against what is in the documentation. Is this expected behavior?
### Steps To Reproduce:

Deploy to a specific org using the mdapi, then attempt to cancel it without specifying the job id.

### Expected result

By running the command without specifying the job id, according to documentation, it should cancel the most recent job.

### Actual result

I got an error, specified above

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.97.0
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:
This command is being run in DroneCI as an automated job

**Comment by shetzel** [comment]
This is not expected behavior.  I suspect that the initial deploy ID is not being written to disk in this environment.  What should happen is that the deploy ID from the initial request is written to ~/.sfdx/stash.json and used by the cancel command.  If you run the deploy command appending `--dev-debug` it might output the reason for the write error (assuming that is the problem).

As a workaround, you could use `--json` for the initial deploy command, save the deploy ID in your script, and use it in the cancel command.

**Comment by trentchilders** [comment]
@shetzel I think you may have hit on the problem in your response. As I mentioned I'm trying to automate deployment validations using DroneCI. So I'm kicking off a deployment validation in one Drone instance (which occurs when a pull request is opened in our SDLC process), but the cancelation command is coming from a different one (when the same branch is updated while the validation is still in process). So there wouldn't be an ~/.sfdx/stash.json in that cancellation request.
The idea was to have sfdx cancel the running job and then rekick off another validation. But it sounds like I can't do that without any context.

 I'll try to grab the job Id and save it down using my controller. Thanks for your response. I'll also close the issue.
